{
  "hash": "6c513a0994f26655dacfb5ae0d2e5a82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Consultation Frequency Analysis\"\n---\n\n\n\n\n## Load Project Setup\n\nThis first chunk sources the `_common.R` script. This single step loads all necessary packages, defines the global `Plot_theme`, and loads the primary `Neuro_Data` (prepared in [Data Cleaning and Processing](0_NeuroColombia_DataCleaning.qmd)) and `Col_map_fixed` data frames into our environment.\n\n\n\n\n\n\n\n\n\n## Consultations per Year\n\nThis section examines how the number of consultations for ICD-10 neurodevelopmental disorders changed over time in Colombia between 2016 and 2022. To provide an overview of long-term patterns, we aggregate the raw consultation records by calendar year. The resulting `Summary_year` dataset contains the total number of consultations reported in each year of the observation period.\n\n### Data Preparation\n\nFirst, we create a summary table by grouping the main `Neuro_Data` by `Year` and summing all `Cases` for each year.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_year <- Neuro_Data %>%\n  group_by(Year) %>%\n  summarise(Total_Cases = sum(Cases, na.rm = TRUE)) %>%\n  ungroup()\n\nSummary_year\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n   Year Total_Cases\n  <int>       <int>\n1  2016      154453\n2  2017      194102\n3  2018      231242\n4  2019      332318\n5  2020      179859\n6  2021      240548\n7  2022      283661\n```\n\n\n:::\n:::\n\n\n\n\n### Data Visualization\n\nWe visualize the yearly trend using a line and point plot. The y-axis labels are formatted with `scales::cut_short_scale()` to automatically display \"K\" for thousands, improving readability.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCases_Year_fig <- Summary_year %>%\n  ggplot( aes(x= Year, y=Total_Cases)) +\n    geom_line( color=\"grey\", linewidth= 2) +\n    geom_point(shape=21, color=\"black\", fill=\"#69b3a2\", size=6) +\n    scale_y_continuous(name = expression (\"Number of consultations\"),\n                     labels = scales::label_number(scale_cut = scales::cut_short_scale())) +\n    ggtitle(\"ICD-10 neurodevelopmental disorders\") +\n    labs(x = \"Year\") +\n    Plot_theme\n\nggsave(Cases_Year_fig,\n       filename = \"Plots/Cases_Year_fig.png\",\n       width    = 14, \n       height   = 12, \n       units    = \"cm\")\n\nCases_Year_fig\n```\n\n::: {.cell-output-display}\n![Distribution of consultation cases for neurodevelopmental disorders per year](1_Consultation_Frequency_files/figure-html/fig-Cases_year-line-1.png){#fig-Cases_year-line width=768}\n:::\n:::\n\n\n\n\nThe temporal trend is visualized using a line plot with points (@fig-Cases_year-line). The annual totals reveal a clear upward trajectory during the pre-pandemic years: consultations increased steadily from 154,453 cases in 2016 to a peak of 332,318 cases in 2019. In 2020, the first year of the COVID-19 pandemic, we observe a sharp decline to 179,859 cases, likely reflecting the widespread disruption of outpatient services and reduced healthcare access.\n\nFollowing this drop, the number of consultations rises again, reaching 240,548 cases in 2021 and 283,661 cases in 2022, though not yet returning to the 2019 peak. This temporal structure provides important context for interpreting subsequent spatial and demographic analyses, and motivates the need to examine how consultation patterns varied across departments and patient subgroups during this period.\n\n## Geographical Distribution\n\nIn this section, we explore how the intensity of neurodevelopmental consultations varies across Colombian departments. Instead of counting raw numbers of cases, we work with a standardized rate that makes regions comparable. For each municipality, we calculate the number of neurodevelopmental consultations per 10,000 individuals in the corresponding reference population (`Diagnostics_per_tenthousand`). The reference population matches the age structure and locality of the reported consultation.\n\n### Data Preparation\n\nWe aggregate municipality-level rates at the departmental level. For each department, we compute the median number of consultations per 10,000 individuals across all municipalities in that department (`MedianCases`). Using the median keeps the summary robust against extreme values from very small or very large localities.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Department <- Neuro_Data %>%\n  group_by(Department) %>%\n  summarise(MedianCases = median(Diagnostics_per_tenthousand, na.rm = TRUE)) %>%\n  ungroup()\n```\n:::\n\n\n\n\n### Results Table\n\nFor clarity, we present a table of the median number of consultations per department, conditioning on the reference population.\n\n\n\n\n::: {#tbl-Department_Summary_Table .cell tbl-cap='Total Cases by Department'}\n\n```{.r .cell-code}\n# Sort data for the table\ndepartment_table_data <- Summary_Department %>%\n  arrange(desc(MedianCases))\n\n# Create the gt table\ndepartment_table <- department_table_data %>%\n  gt() %>%\n  cols_label(\n    Department = \"Department\",\n    MedianCases = \"Median Cases\"\n  ) %>%\n  fmt_number(\n    columns = MedianCases,\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n  theme_apa_gt()\n\n# Save the table files\ngtsave(department_table,\n       filename = \"Tables/Department_Summary_Table.html\")\ngtsave(department_table,\n       filename = \"Tables/Department_Summary_Table.tex\")\n\ndepartment_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ihsomtkdtj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ihsomtkdtj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ihsomtkdtj thead, #ihsomtkdtj tbody, #ihsomtkdtj tfoot, #ihsomtkdtj tr, #ihsomtkdtj td, #ihsomtkdtj th {\n  border-style: none;\n}\n\n#ihsomtkdtj p {\n  margin: 0;\n  padding: 0;\n}\n\n#ihsomtkdtj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ihsomtkdtj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ihsomtkdtj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ihsomtkdtj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ihsomtkdtj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ihsomtkdtj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ihsomtkdtj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ihsomtkdtj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ihsomtkdtj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ihsomtkdtj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ihsomtkdtj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ihsomtkdtj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ihsomtkdtj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ihsomtkdtj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ihsomtkdtj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ihsomtkdtj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ihsomtkdtj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ihsomtkdtj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ihsomtkdtj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ihsomtkdtj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ihsomtkdtj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ihsomtkdtj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ihsomtkdtj .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ihsomtkdtj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ihsomtkdtj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ihsomtkdtj .gt_left {\n  text-align: left;\n}\n\n#ihsomtkdtj .gt_center {\n  text-align: center;\n}\n\n#ihsomtkdtj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ihsomtkdtj .gt_font_normal {\n  font-weight: normal;\n}\n\n#ihsomtkdtj .gt_font_bold {\n  font-weight: bold;\n}\n\n#ihsomtkdtj .gt_font_italic {\n  font-style: italic;\n}\n\n#ihsomtkdtj .gt_super {\n  font-size: 65%;\n}\n\n#ihsomtkdtj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ihsomtkdtj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ihsomtkdtj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ihsomtkdtj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ihsomtkdtj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ihsomtkdtj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ihsomtkdtj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ihsomtkdtj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ihsomtkdtj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Department\">Department</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MedianCases\">Median Cases</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Narino</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">97</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Boyaca</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">78</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Caldas</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">51</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Tolima</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">48</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Sucre</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">47</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cundinamarca</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">45</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Huila</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">43</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Putumayo</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">43</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Quindio</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">42</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cauca</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">41</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Bolivar</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">39</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Risaralda</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">37</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Choco</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">36</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Caqueta</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">35</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Casanare</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">35</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Santander</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">34</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Antioquia</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">29</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Norte de Santander</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">29</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Vichada</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">28</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Archipielago de San Andres, Providencia Y Santa Catalina</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">26</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cesar</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">26</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Guainia</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">26</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Atlantico</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">23</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cordoba</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">22</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Valle del Cauca</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">22</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Vaupes</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">22</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Arauca</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">21</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">La Guajira</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">21</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Meta</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">20</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Amazonas</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">18</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Guaviare</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">18</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Magdalena</td>\n<td headers=\"MedianCases\" class=\"gt_row gt_right\">16</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe resulting table ranks departments by their median rate of consultations. Departments such as Nariño (median 97 consultations per 10,000 individuals), Boyacá (78), Caldas (51), Tolima (48), and Sucre (47) stand out with the highest typical consultation intensities.\n\n### Generating a Map of Colombia\n\nTo visualize this pattern, we join the departmental summaries with the GADM shapefile and generate a choropleth map of Colombia. Each department appears with a color that reflects its median consultation rate. This map highlights clusters of high and low consultation intensity and helps identify regions where the healthcare system records more frequent neurodevelopmental assessments relative to the local population.\n\nTo join the case data with the map geometry, we use the `Col_map_fixed` object (loaded from `_common.R`) and perform a `left_join` with our `Summary_Department` data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMap_df <- Col_map_fixed %>%\n  left_join(Summary_Department, by = \"Department\")\n```\n:::\n\n\n\n\n### Consultation by Department\n\nWe plot the total number of cases by department. To highlight the most-affected regions, we create a `top_5_data` subset and use `geom_sf_text` to overlay their labels on the map. The fill scale is square-root-transformed (`trans = \"sqrt\"`) to better visualize the distribution, and labels are formatted to \"K\" for thousands.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for the top 5 labels\ntop_5_data <- Map_df %>%\n  slice_max(order_by = MedianCases, n = 5)\n\n# Create the map\nDepartment_map <- ggplot(Map_df) +\n  geom_sf(aes(fill = MedianCases), colour = \"white\", size = 0.2) +\n  \n  # Add the text labels for the top 5\n  geom_sf_text(\n    data = top_5_data,\n    aes(label = Department), \n    color = \"white\",\n    size = 5,\n    check_overlap = TRUE\n  ) +\n  \n  scale_fill_viridis_c(\n    option    = \"viridis\",\n    direction = -1,\n    trans     = \"sqrt\",   \n    name      = \"Median number of consultations \\nper 10.000 (reference population)\",\n    guide = guide_colorbar(\n      barwidth     = unit(12, \"cm\"),  \n      barheight    = unit(0.8, \"cm\")  \n    )\n  ) +\n  labs(title = \"Consultations per department (2016-2022)\") +\n  theme_minimal() +\n  Plot_theme +\n  theme(\n    plot.title = element_text(size=22, face=\"bold\", vjust = 2),\n    axis.text.y = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.y = element_blank(),\n    axis.ticks.x = element_blank(),\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    legend.title = element_text(colour=\"black\", face=\"bold\", size=16),\n    legend.text = element_text(colour=\"black\", size=16),\n    strip.text = element_text(size = 20)\n  ) \n\nggsave(Department_map,\n       filename = \"Plots/Department_map.png\",\n       width    = 22, \n       height   = 25, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\n```\n\n\n:::\n\n```{.r .cell-code}\nDepartment_map\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Cases by department and capital status](1_Consultation_Frequency_files/figure-html/fig-Department_map-1.png){#fig-Department_map width=768}\n:::\n:::\n\n\n\n\n## Consultations Conditional on Capital City\n\nIn this section, we examine how consultation intensity differs between departmental capitals and the rest of the municipalities. We calculate the consultation rate for each municipality as the number of neurodevelopmental consultations per 10,000 individuals in the matched reference population. We then group municipalities by whether they belong to a departmental capital and summarize each group using the median and standard deviation.\n\n### Data Preparation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Capital <- Neuro_Data %>%\n  group_by(Capital, Department) %>%\n  summarise(\n  Median_Cases_Capitals = median(Diagnostics_per_tenthousand, na.rm = TRUE),\n  ) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Capital'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n:::\n\n\n\n\n### Data Visualization\n\nWe use a ridge plot (`ggridges`) to visualize the distribution of median consultation rates, comparing capital and non-capital departments. To make the plot more informative, we pre-calculate the Median and SD for each group and overlay this text directly onto the plot using `geom_text`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggridges) # For the ridge plot\nlibrary(dplyr)    # For calculating the stats\n\n# --- 1. Create the summary statistics data frame ---\n# We calculate the median and SD for each 'Capital' group\nstats_data <- Summary_Capital %>%\n  group_by(Capital) %>%\n  summarise(\n    Median = median(Median_Cases_Capitals, na.rm = TRUE),\n    SD = sd(Median_Cases_Capitals, na.rm = TRUE)\n  ) %>%\n  ungroup() %>%\n  # Create a text label with line breaks (\\n)\n  mutate(\n    summary_label = sprintf(\"Median: %.1f\\nSD: %.1f\", Median, SD)\n  )\n\n# --- 2. Create the plot ---\nCases_Capital_fig <- Summary_Capital %>%\n  ggplot(aes(x = Median_Cases_Capitals, y = Capital, fill = Capital)) +\n  \n  # Draw the ridges\n  geom_density_ridges(alpha = 0.7) +\n  \n  # --- 3. Add the summary text ---\n  # We use the new 'stats_data' data frame\n  # inherit.aes = FALSE stops it from interfering with the main plot\n  geom_text(\n    data = stats_data,\n    inherit.aes = FALSE,\n    # Place text at the Median (x) and on the correct Capital ridge (y)\n    aes(x = Median, y = Capital, label = summary_label), \n    color = \"black\",  # Text color\n    size = 3.5,       # Text size\n    vjust = -0.5,     # Vertical justification (move text *up*)\n    hjust = -0.5         # Horizontal justification (start text at the median)\n  ) +\n  \n  ggtitle(\"\") +\n  \n  scale_fill_manual(\n    name = \"Capital city\",\n    values = c(\"#D9717D\", \"#4DB6D0\"),\n    labels = c(\"No\", \"Yes\")\n  ) +\n  \n  labs(y = \"Capital city status\",\n       x = \"Median number of consultations \\n per 10.000 (reference population)\") +\n  \n  # Widen the x-axis to make room for the text\n  scale_x_continuous(expand = expansion(mult = c(0.05, 0.2))) +\n  \n  Plot_theme +\n  theme (legend.position = \"none\",\n         axis.text.x = element_text(hjust = 1)) \n\nggsave(Cases_Capital_fig,\n       filename = \"Plots/Cases_Capital_fig.png\",\n       width    = 14,\n       height   = 12, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPicking joint bandwidth of 6.21\n```\n\n\n:::\n\n```{.r .cell-code}\nCases_Capital_fig\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPicking joint bandwidth of 6.21\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of median neurodevelopmental diagnostic cases by capital status, with summary statistics.](1_Consultation_Frequency_files/figure-html/fig-Diagnostics_capital-ridges-stats-1.png){#fig-Diagnostics_capital-ridges-stats width=768}\n:::\n:::\n\n\n\n\nWe visualize these distributions using a density ridgeline plot, which makes the difference in scale immediately visible. Departmental capital cities report a median of 8 consultations per 10,000 inhabitants (SD = 10), whereas non-capital municipalities show a much higher median of 51.5 consultations per 10,000 inhabitants (SD = 111.7). This pattern suggests that individuals living outside departmental capitals tend to engage more with neurodevelopmental services relative to their population size, even though capital cities host the largest and most specialized medical centers.\n\n## Geographical Distribution by Sex\n\nIn this section, we examine how consultation intensity differs between men and women across Colombian departments. Using the population-standardized rate of neurodevelopmental consultations per 10,000 inhabitants, we first summarize the median rate for each sex within each department across all available years. This aggregation produces a sex-stratified map of consultation intensity that allows direct comparison between regions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nSummary_Sex <- Neuro_Data %>%\n  group_by(Department, Sex) %>%\n  summarise(\n    MedianCases = round(median(Diagnostics_per_tenthousand, na.rm = TRUE), digits = 0),\n  ) %>%\n  ungroup() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Department'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n:::\n\n\n\n\nWe join this information to the Colombian map:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMap_df <- Col_map_fixed %>%\n  left_join(Summary_Sex, by = \"Department\")\n\n#We exclude NAs\nMap_df <- Map_df %>%\n  filter(!is.na(MedianCases))\n```\n:::\n\n\n\n\nThen, we use `geom_sf` to plot the resulting maps and label the top ten counts:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_10_data <- Map_df %>%\n  slice_max(order_by = MedianCases, n = 10)\n\nCases_Sex_map <- ggplot(Map_df) +\n  geom_sf(aes(fill = MedianCases), colour = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    option    = \"viridis\",\n    limits = c(0, 120),\n    direction = -1,\n    name      = \"Median number of consultations \\nper 10.000 (reference population)\",\n    guide = guide_colorbar(\n      barwidth        = unit(10, \"cm\"),  \n      barheight       = unit(0.5, \"cm\")   \n    )\n  ) +\n  \n  # Add the text labels for the top 10\n  geom_sf_text(\n    data = top_10_data,\n    aes(label = Department), \n    color = \"black\",\n    size = 4,\n    check_overlap = TRUE\n  ) +\n  \n  facet_wrap(~ Sex) +\n  labs(title = \"Consultation per biological sex\") +\n  theme_minimal() +\n  Plot_theme +\n  theme(\n    axis.text.y = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.y = element_blank(),\n    axis.ticks.x = element_blank(),\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    strip.text = element_text(size = 12)\n  ) \n\nggsave(Cases_Sex_map,\n       filename = \"Plots/Cases_Sex_map.png\",\n       width    = 25, \n       height   = 15, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\n```\n\n\n:::\n\n```{.r .cell-code}\nCases_Sex_map \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\nWarning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not\ngive correct results for longitude/latitude data\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of consultations per department and capital city status](1_Consultation_Frequency_files/figure-html/fig-Cases_Sex-Map-1.png){#fig-Cases_Sex-Map width=1152}\n:::\n:::\n\n\n\n\nWe observe that the resulting distribution is not uniform in @fig-Cases_Sex-Map. Men show several departments with particularly high consultation rates, including Nariño (109 per 10,000), Boyacá (85), Caldas (57), Cundinamarca (52), and Putumayo (51). Women show a similar pattern but with overall lower values; the highest consultation rates occur in Nariño (89) and Boyacá (65). These sex-specific maps highlight areas where diagnostic engagement is substantially higher for one group than the other and provide geographical context for interpreting the statistical models developed in later sections.\n\n## Statistical Modeling\n\nWe model the mean consultation rate as a function of biological sex, allowing both the **baseline level** and the **sex effect** to vary across departments. This structure lets each department have its own overall consultation level and its own difference between men and women, while still borrowing strength across departments.\n\nFirst, we write the likelihood using a Student-t distribution to remain robust to extreme values:\n\n$$\n\\text{MeanCases}_{ij} \\sim \\text{Student}(\\nu,\\; \\mu_{ij},\\; \\sigma)\n$$\n\nwhere $\\nu$ is the degrees-of-freedom parameter, $\\sigma$ is the residual scale, and the linear predictor $\\mu_{ij}$ is\n\n$$\n\\mu_{ij}\n= \\beta_0 + \\beta_{\\text{Sex}} \\,\\text{Sex}_{ij}\n+ u_{0j} + u_{1j}\\,\\text{Sex}_{ij}.\n$$\n\nExplanation of terms in the linear predictor:\n\n-   $\\beta_0$: global intercept (mean rate for men in an average department)\n-   $\\beta_{\\text{Sex}}$: global average difference between women and men\n-   $u_{0j}$: department-specific deviation from the global intercept (random intercept)\n-   $u_{1j}$: department-specific deviation from the global sex effect (random slope for Sex)\n\nWe collect the department-level random effects in a bivariate normal distribution:\n\n$$\n\\begin{pmatrix}\nu_{0j} \\\\\nu_{1j}\n\\end{pmatrix}\n\\sim\n\\mathcal{N}\\!\\left(\n\\begin{pmatrix}\n0 \\\\\n0\n\\end{pmatrix},\n\\;\n\\begin{pmatrix}\n\\sigma_{\\text{int}}^{2} &\n\\rho\\,\\sigma_{\\text{int}}\\sigma_{\\text{sex}} \\\\\n\\rho\\,\\sigma_{\\text{int}}\\sigma_{\\text{sex}} &\n\\sigma_{\\text{sex}}^{2}\n\\end{pmatrix}\n\\right).\n$$\n\nWhere:\n\n-   $\\sigma_{\\text{int}}$: standard deviation of department intercepts (between-department differences in baseline rate)\n-   $\\sigma_{\\text{sex}}$: standard deviation of department-specific sex effects\n-   $\\rho$: correlation between intercepts and sex effects\n\nWe fit this hierarchical Student-t model in **brms** using four MCMC chains with 5,000 iterations each (2,500 warmup). We set a high `adapt_delta` and `max_treedepth` to obtain stable sampling for the heavy-tailed likelihood and the random-effects structure. We rely on the default weakly informative priors defined by **brms**, so we do not inject additional substantive information into the model beyond the data.\n\n### Prepare the Data\n\nWe rewrite the `Summary_Sex` variable to have cities as observations to make a more precise estimation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Sex <- Neuro_Data %>%\n  group_by(City, Department, Sex) %>%\n  summarise(\n    MeanCases = round(mean(Diagnostics_per_tenthousand, na.rm = TRUE), digits = 0),\n  ) %>%\n  ungroup() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'City', 'Department'. You can override\nusing the `.groups` argument.\n```\n\n\n:::\n:::\n\n\n\n\n### Fit the Model\n\nWe use `brms` to fit our hierarchical model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model formula\nCases_Sex_Mdl1 <- bf(MeanCases ~ Sex + (Sex | Department))\n               \n# List priors and variables\nget_prior(Cases_Sex_Mdl1, Summary_Sex, family = student)\n\n# Fit model 1\nCases_Sex_Fit1 <- \n  brm(\n    family  = student,\n    data    = Summary_Sex,\n    formula = Cases_Sex_Mdl1,\n    chains  = 4,\n    cores   = 4,\n    warmup  = 2500, \n    iter    = 5000, \n    seed    = 8807,\n    control = list(adapt_delta = 0.99, max_treedepth = 15),\n    file    = \"Models/Cases_Sex_Fit1.rds\",\n    file_refit = \"never\")\n```\n:::\n\n\n\n\n### Model Results\n\nThe hierarchical model quantifies how consultation intensity differs between sexes after accounting for geographical variation. The intercept represents the expected mean number of consultations per 10,000 inhabitants for men, averaged across departments and years.\n\n\n\n\n::: {#tbl-Cases_Sex .cell}\n\n```{.r .cell-code}\ntbl_cases_sex <- tbl_regression(\n  x            = Cases_Sex_Fit1,\n  intercept    = TRUE,\n  estimate_fun = ~ style_sigfig(., digits = 2),\n  conf.level   = 0.95\n) %>%\n  modify_header(\n    label    ~ \"**Predictor**\",\n    estimate ~ \"**Estimate**\",\n    ci       ~ \"**95% CI**\"\n  ) %>%\n  bold_labels() %>%\n  modify_caption(\n    \"**Table 1. Effect of biological sex on neurodevelopmental consultation rates**\"\n  )\n\ntbl_cases_sex \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rmkezyqhvh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rmkezyqhvh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rmkezyqhvh thead, #rmkezyqhvh tbody, #rmkezyqhvh tfoot, #rmkezyqhvh tr, #rmkezyqhvh td, #rmkezyqhvh th {\n  border-style: none;\n}\n\n#rmkezyqhvh p {\n  margin: 0;\n  padding: 0;\n}\n\n#rmkezyqhvh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rmkezyqhvh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rmkezyqhvh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rmkezyqhvh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rmkezyqhvh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rmkezyqhvh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rmkezyqhvh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rmkezyqhvh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rmkezyqhvh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rmkezyqhvh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rmkezyqhvh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rmkezyqhvh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rmkezyqhvh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rmkezyqhvh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rmkezyqhvh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmkezyqhvh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rmkezyqhvh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rmkezyqhvh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rmkezyqhvh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmkezyqhvh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rmkezyqhvh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmkezyqhvh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rmkezyqhvh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmkezyqhvh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rmkezyqhvh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmkezyqhvh .gt_left {\n  text-align: left;\n}\n\n#rmkezyqhvh .gt_center {\n  text-align: center;\n}\n\n#rmkezyqhvh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rmkezyqhvh .gt_font_normal {\n  font-weight: normal;\n}\n\n#rmkezyqhvh .gt_font_bold {\n  font-weight: bold;\n}\n\n#rmkezyqhvh .gt_font_italic {\n  font-style: italic;\n}\n\n#rmkezyqhvh .gt_super {\n  font-size: 65%;\n}\n\n#rmkezyqhvh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rmkezyqhvh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rmkezyqhvh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rmkezyqhvh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rmkezyqhvh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rmkezyqhvh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rmkezyqhvh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rmkezyqhvh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rmkezyqhvh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption><span data-qmd-base64=\"PHN0cm9uZz5UYWJsZSAxLiBFZmZlY3Qgb2YgYmlvbG9naWNhbCBzZXggb24gbmV1cm9kZXZlbG9wbWVudGFsIGNvbnN1bHRhdGlvbiByYXRlczwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Table 1. Effect of biological sex on neurodevelopmental consultation rates</strong></span></span></caption>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5QcmVkaWN0b3I8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>Predictor</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5Fc3RpbWF0ZTwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Estimate</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">94</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">77,  112</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">77, 112</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SexWomen</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-5.0</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-11,  1.1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-11, 1.1</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDcmVkaWJsZSBJbnRlcnZhbA==\"><span class='gt_from_md'>CI = Credible Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe intercept in @tbl-Cases_Sex represents the expected mean number of consultations per 10,000 inhabitants for men in an average department. The model estimates this baseline at 94 consultations (95 % CI: 77–112), which reflects the national-level average once we account for department-level heterogeneity. The coefficient for Women (`SexWomen`) captures the global average difference in consultation rate between women and men across the country. The model estimates this effect as −5 consultations per 10,000 inhabitants (95 % CI: −11 to −1.1). This negative estimate indicates that, on average, women show lower consultation rates than men. Importantly, this fixed effect represents the population-level average, while the random slope structure in the model allows each department to deviate from this mean sex effect.\n\nWe save the results tables as LaTeX and Word documents:\n\n\n\n\n\n\n\n\n\n#### Posterior Draws\n\nThe hierarchical model allows us to generate posterior predictive distributions for the consultation rate of men and women, while incorporating uncertainty in both the fixed effects and the department-specific random effects. Using the fitted model, we draw predictions for each combination of sex and department and summarize these draws.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(8807)\n\nsex_predicted_draws <- Summary_Sex %>%\n  group_by(Sex, Department) %>% # Ensure we consider the department-level grouping\n  add_predicted_draws(Cases_Sex_Fit1, re_formula = NA) # re_formula = NA to include all random effects\n\n# Plotting\nCases_Sex_Fig1 <- ggplot(sex_predicted_draws, aes(x = Sex, y = .prediction, fill = Sex)) +\n  stat_halfeye() + \n  geom_jitter(data = Summary_Sex, aes(x = Sex, y = MeanCases, color = Sex),\n              width = 0.2, alpha = 0.4, size = 0.4) + \n  geom_point(data = sex_predicted_draws %>% group_by(Sex, Department) %>% summarise(MeanCases = mean(.prediction)), \n             aes(x = Sex, y = MeanCases, color = Sex), \n             shape = 1, size = 2, show.legend = FALSE) + \n \n  labs(caption = \"Model: MeanCases ~ Sex + (Sex | Department)\",\n       y = \"Mean number of consultations \\nper 10.000 (reference population)\",\n       x = \"\") +\n  ylim(0, 600) +\n  Plot_theme +\n  theme(legend.position = \"none\") +\n  theme(text = element_text(size = 24)) +\n  coord_flip()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Sex'. You can override using the `.groups`\nargument.\n```\n\n\n:::\n\n```{.r .cell-code}\nggsave(Cases_Sex_Fig1,\n       filename = \"Plots/Cases_Sex_Fig1.png\",\n       width    = 12, \n       height   = 10, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3193787 rows containing missing values or values outside the scale\nrange (`stat_slabinterval()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 68 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n```{.r .cell-code}\nCases_Sex_Fig1 \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3193787 rows containing missing values or values outside the scale\nrange (`stat_slabinterval()`).\nRemoved 68 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Posterior distribution for the number of neurodevelopmental diagnostics per biological sex](1_Consultation_Frequency_files/figure-html/fig-Sex_Posterior-1.png){#fig-Sex_Posterior width=768}\n:::\n:::\n\n\n\n\nThe coloured half-eye shapes represent the posterior predictive distribution of the mean number of consultations per 10,000 inhabitants for each sex, averaged across departments. The open circles show the average predicted value for each sex, and the horizontal black intervals mark the corresponding 95% credible intervals. We overlay the observed department-by-year means as jittered points, which lets us visually compare the model-based predictions with the empirical data.\n\nThe posterior distributions for men and women clearly separate. At the same time, the observed points for both sexes fall largely within the corresponding predictive distributions, indicating that the model captures the magnitude and spread of the data reasonably well.\n\n#### Contrast Between Biological Sex\n\nTo summarize the overall effect of biological sex, we extract the posterior samples of the fixed effect for women (`b_SexWomen`) from the hierarchical model. This coefficient represents the *average* difference in consultation rate between women and men across all departments, after accounting for department-specific intercepts and sex slopes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract posterior samples for the treatment effect\nsex_posterior_samples <- posterior_samples(Cases_Sex_Fit1, pars = c(\"b_SexWomen\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Method 'posterior_samples' is deprecated. Please see ?as_draws for\nrecommended alternatives.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Convert to a data frame for ggplot\nsex_posterior_df <- as.data.frame(sex_posterior_samples)\n\n# Visualizing the Treatment effect size with uncertainty\nCases_Sex_Fig2 <- ggplot(sex_posterior_df, aes(x = b_SexWomen)) +\n  stat_halfeye() +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\", size = 1) +\n  labs(title = \"Mean number of consultations\",\n    caption = \"Model: MeanCases ~ Sex + (Sex | Department)\",\n    x = \"Effect Size (Women)\",\n       y = \"Density\") +\n  Plot_theme +\n  theme(text = element_text(size = 30))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nggsave(Cases_Sex_Fig2,\n       filename = \"Plots/Cases_Sex_Fig2.png\",\n       width    = 12, \n       height   = 10, \n       units    = \"cm\")\n\nCases_Sex_Fig2 \n```\n\n::: {.cell-output-display}\n![Effect size for Women](1_Consultation_Frequency_files/figure-html/fig-Cases_Sex-Contrast-1.png){#fig-Cases_Sex-Contrast width=768}\n:::\n:::\n\n\n\n\n@fig-Cases_Sex-Contrast shows the posterior distribution of this global sex effect. The horizontal axis corresponds to the difference in the mean number of consultations per 10,000 inhabitants for women relative to men. The vertical dashed line at zero marks the point of no difference between sexes. The posterior mass lies entirely below zero, with a posterior mean of approximately −8.6 consultations per 10,000 inhabitants and a 95% credible interval from −11 to −6.1. This distribution indicates that, on average, women have lower consultation rates than men.\n\n#### Department-level Variability in Baseline Consultation Rates\n\nTo quantify how much departments differ in their overall consultation intensity, we examine the posterior distribution of the standard deviation of the department intercepts. This parameter $\\sigma_{\\text{int}}$ measures the spread of the department-specific baseline effects after we adjust for sex and allow sex differences to vary by department.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract posterior samples for the random effect\ndepartment_posterior_samples <- posterior_samples(Cases_Sex_Fit1, pars = c(\"^sd_\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Method 'posterior_samples' is deprecated. Please see ?as_draws for\nrecommended alternatives.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Convert to a data frame for ggplot\ndepartment_posterior_df <- as.data.frame(department_posterior_samples)\n\n# Visualizing the Treatment effect size with uncertainty\nCases_Sex_Fig3 <- ggplot(department_posterior_df, aes(x = sd_Department__Intercept)) +\n  stat_halfeye() +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\", size = 1) +\n  labs(caption = \"Model: Cases ~ Sex + (sex | Department)\",\n       x = \"Department (sd)\",\n       y = \"Density\") +\n  Plot_theme +\n  theme(text = element_text(size = 30))\n\nggsave(Cases_Sex_Fig3,\n       filename = \"Plots/Cases_Sex_Fig3.png\",\n       width    = 12, \n       height   = 10, \n       units    = \"cm\")\n\nCases_Sex_Fig3 \n```\n\n::: {.cell-output-display}\n![Standart deviation for the random effects variable (department)](1_Consultation_Frequency_files/figure-html/fig-Sex_Departmentsd-1.png){#fig-Sex_Departmentsd width=768}\n:::\n:::\n\n\n\n\n@fig-Sex_Departmentsd displays the posterior distribution of this standard deviation. The entire distribution lies far from zero and concentrates around relatively large values, indicating marked variability in baseline consultation rates across departments. In other words, even before considering sex-specific differences, some departments show much higher overall consultation rates than others. This result complements the descriptive maps and confirms that geographical heterogeneity is a central feature of the data.\n\n#### Department-specific Effects of Biological Sex\n\nBecause our model includes a random slope for sex, we can examine how the effect of being a woman varies across departments. For each department, we combine the global sex effect (`b_SexWomen`) with the department-specific deviation in the sex slope to obtain a posterior distribution of the sex effect in that department. These department-level effects represent the difference in mean consultation rate between women and men (women minus men) on the scale of cases per 10,000 inhabitants.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Posterior draws for fixed and random sex effects\npost <- posterior_samples(Cases_Sex_Fit1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Method 'posterior_samples' is deprecated. Please see ?as_draws for\nrecommended alternatives.\n```\n\n\n:::\n\n```{.r .cell-code}\nsex_draws_long <- post %>%\n  mutate(.draw = row_number()) %>%\n  # keep global sex effect + all department random effects\n  select(.draw, b_SexWomen, starts_with(\"r_Department[\")) %>%\n  # reshape to long format\n  pivot_longer(\n    starts_with(\"r_Department[\"),\n    names_to  = \"param\",\n    values_to = \"r_SexWomen\"\n  ) %>%\n  # keep only random slopes for SexWomen\n  filter(str_detect(param, \",SexWomen\\\\]\")) %>%\n  # extract department name between \"[\" and \",SexWomen]\"\n  mutate(\n    Department = str_extract(param, \"(?<=\\\\[).*(?=,SexWomen\\\\])\"),\n    sex_effect_dept = b_SexWomen + r_SexWomen\n  )\n\n# 2. Plot department-specific sex effects\nCases_Sex_Fig4 <- ggplot(\n  sex_draws_long,\n  aes(x = sex_effect_dept,\n      y = reorder(Department, sex_effect_dept))\n) +\n  stat_halfeye(color = \"black\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\",\n             color = \"red\", linewidth = 1) +\n  scale_y_discrete(labels = function(x) recode(x,\n    \"Valle.del.Cauca\"            = \"Valle\",\n    \"La.Guajira\"                = \"Guajira\",\n    \"Archipielago.de.San.Andres,.Providencia.Y.Santa.Catalina\" = \"San Andrés\",\n    \"Norte.de.Santander\"         = \"N. Santander\"\n  )) +\n  labs(\n    caption = \"Model: MeanCases ~ Sex + (Sex | Department)\",\n    x       = \"Sex effect (Women – Men, cases per 10,000)\",\n    y       = \"Department\"\n  ) +\n  Plot_theme +\n  theme(text = element_text(size = 30))\n\nggsave(\n  Cases_Sex_Fig4,\n  filename = \"Plots/Cases_Sex_Fig4.png\",\n  width    = 18,\n  height   = 20,\n  units    = \"cm\"\n)\n\nCases_Sex_Fig4\n```\n\n::: {.cell-output-display}\n![Department-specific effects of biological sex on consultation rates](1_Consultation_Frequency_files/figure-html/fig-Cases_Sex-DepartmentSex-1.png){#fig-Cases_Sex-DepartmentSex width=768}\n:::\n:::\n\n\n\n\n@fig-Cases_Sex-DepartmentSex displays posterior distributions. Each half-eye corresponds to one department. Negative values indicate departments where women have lower consultation rates than men, whereas positive values would indicate the opposite. The vertical dashed line at zero marks the point of no difference between sexes.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}