{
  "hash": "a9683913b82d3fd6ce0f4bc84d7c7f4c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Deep Dive: Top 3 Diagnostics\"\n---\n\n\n\n\n## Load Project Setup and Data\n\nThis first chunk sources the `_common.R` script, which loads all packages, the `Plot_theme`, and the cleaned `Col_map_fixed` object.\n\nIt then **loads the subsetted data (`Neuro_Data_MainDiag.csv`)** that was created by the previous notebook (see [Diagnostic Frequency Analysis](2_Consultation_DiagnosticFrecuency.qmd)). All analysis in this file will be based on this \"Top 3\" dataset.\n\n\n\n\n\n\n\n\n\n## Geographical Distribution of Most Frequent Cases\n\nWe examine how the three most common neurodevelopmental diagnoses are distributed across Colombian departments. This analysis focuses on median consultation rates per 10,000 inhabitants, which allows us to compare regions while minimizing the influence of extreme values.\n\n### Data Preparation\n\nWe begin by summarizing the consultation frequency for each of the three focal diagnostic categories within every department. The data are grouped by Department and Diagnostic, and we compute the median number of consultations per 10,000 inhabitants. This measure gives a stable central estimate for each diagnostic–department combination.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Common_Geography <- Neuro_Data_MainDiag %>%\n  group_by(Department, Diagnostic) %>%\n  summarise(\n    MedianCases = median(Diagnostics_per_tenthousand, na.rm = TRUE),\n  ) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Department'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n:::\n\n\n\n\n### Results Table\n\nTo facilitate comparison across regions, we reshape the dataset so that each diagnostic category occupies its own column. The resulting wide-format table includes the median frequency for each diagnostic, along with a Total column that sums all three (\"F808\", \"F809\", \"F900\"). Departments are then ordered from highest to lowest total case burden.\n\n\n\n\n::: {#tbl-Geo_Summary .cell tbl-cap='Total Cases by Department and Main Diagnostic'}\n\n```{.r .cell-code}\n# --- 1. Pivot the data to wide format ---\nwide_geo_summary <- Summary_Common_Geography %>%\n  pivot_wider(\n    names_from = Diagnostic,\n    values_from = MedianCases,\n    values_fill = 0\n  ) %>%\n  mutate(Total_All_Cases = rowSums(across(where(is.numeric)))) %>%\n  arrange(desc(Total_All_Cases))\n\n# --- 2. Create APA-style gt table ---\ngeo_table <- wide_geo_summary %>%\n  gt() %>%\n  tab_header(\n    title = md(\"**Table 2. Median neurodevelopmental consultations per 10.000 inhabitants**\")\n  ) %>%\n  cols_label(\n    Department      = \"Department\",\n    Total_All_Cases = \"Total\"\n  ) %>%\n  fmt_number(\n    columns = where(is.numeric),\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n  # APA 7 styling\n  theme_apa_gt() %>%\n  tab_source_note(\n    source_note = \"Median number of consultations per 10,000 inhabitants, grouped by department and diagnostic category.\"\n  )\n\n# --- 3. Save files ---\ngtsave(geo_table, filename = \"Tables/Geo_Summary.html\")\ngtsave(geo_table, filename = \"Tables/Geo_Summary.tex\")\n\ngeo_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zstuymyowm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zstuymyowm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zstuymyowm thead, #zstuymyowm tbody, #zstuymyowm tfoot, #zstuymyowm tr, #zstuymyowm td, #zstuymyowm th {\n  border-style: none;\n}\n\n#zstuymyowm p {\n  margin: 0;\n  padding: 0;\n}\n\n#zstuymyowm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zstuymyowm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zstuymyowm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zstuymyowm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zstuymyowm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zstuymyowm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zstuymyowm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zstuymyowm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zstuymyowm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zstuymyowm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zstuymyowm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zstuymyowm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zstuymyowm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zstuymyowm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zstuymyowm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zstuymyowm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zstuymyowm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zstuymyowm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zstuymyowm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zstuymyowm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zstuymyowm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zstuymyowm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zstuymyowm .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zstuymyowm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zstuymyowm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zstuymyowm .gt_left {\n  text-align: left;\n}\n\n#zstuymyowm .gt_center {\n  text-align: center;\n}\n\n#zstuymyowm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zstuymyowm .gt_font_normal {\n  font-weight: normal;\n}\n\n#zstuymyowm .gt_font_bold {\n  font-weight: bold;\n}\n\n#zstuymyowm .gt_font_italic {\n  font-style: italic;\n}\n\n#zstuymyowm .gt_super {\n  font-size: 65%;\n}\n\n#zstuymyowm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zstuymyowm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zstuymyowm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zstuymyowm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zstuymyowm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zstuymyowm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zstuymyowm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zstuymyowm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zstuymyowm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style><span data-qmd-base64=\"PHN0cm9uZz5UYWJsZSAyLiBNZWRpYW4gbmV1cm9kZXZlbG9wbWVudGFsIGNvbnN1bHRhdGlvbnMgcGVyIDEwLjAwMCBpbmhhYml0YW50czwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Table 2. Median neurodevelopmental consultations per 10.000 inhabitants</strong></span></span></td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Department\">Department</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F808\">F808</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F809\">F809</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F900\">F900</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total_All_Cases\">Total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Narino</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">139</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">128</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">142</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">408</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Boyaca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">128</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">119</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">84</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">331</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Santander</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">79</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">84</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">97</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">260</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Caldas</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">70</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">93</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">237</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cundinamarca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">75</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">82</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">70</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">227</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Tolima</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">75</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">76</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">64</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">215</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Quindio</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">58</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">103</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">212</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Putumayo</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">68</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">50</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">192</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Risaralda</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">85</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">189</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Casanare</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">55</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">58</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">61</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">174</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Sucre</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">52</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">69</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">174</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Norte de Santander</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">57</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">60</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">56</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">173</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Choco</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">54</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">65</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">172</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Archipielago de San Andres, Providencia Y Santa Catalina</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">48</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">47</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">70</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">166</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Huila</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">52</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">63</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">46</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">161</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cauca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">60</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">59</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">40</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">159</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Bolivar</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">47</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">44</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">67</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">158</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Antioquia</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">43</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">38</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">76</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">157</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Caqueta</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">56</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">46</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">155</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Valle del Cauca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">48</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">45</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">144</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Atlantico</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">39</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">38</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">65</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">142</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Meta</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">48</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">38</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">136</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Vichada</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">20</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">46</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">50</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">116</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Arauca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">41</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">40</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">34</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">115</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cesar</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">37</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">41</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">37</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">115</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Guaviare</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">36</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">50</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">18</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">103</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cordoba</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">29</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">31</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">36</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">96</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Magdalena</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">34</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">31</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">31</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">96</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">La Guajira</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">23</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">33</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">31</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">87</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Amazonas</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">33</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">18</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">84</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Guainia</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">26</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">27</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">26</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">79</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Vaupes</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">22</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">21</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">21</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">64</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"5\">Median number of consultations per 10,000 inhabitants, grouped by department and diagnostic category.</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nAfter summarizing the median burden of the three most frequent neurodevelopmental diagnostic categories (F808, F809, F900) across all departments in @tbl-Geo_Summary, we identify the ten departments with the highest combined consultation rates and extract them using `slice_max()` on the total median burden.\n\n\n\n\n::: {#tbl-Geo_Top10 .cell tbl-cap='Top 10 departments by median neurodevelopmental consultations'}\n\n```{.r .cell-code}\nlibrary(gt)\n\n# --- 1. Select the top 10 departments by total burden ---\ngeo_top10 <- wide_geo_summary %>%\n  slice_max(Total_All_Cases, n = 10)\n\n# --- 2. Create APA-style gt table ---\ngeo_top10_gt <- geo_top10 %>%\n  gt() %>%\n  tab_header(\n    title = md(\"**Table X. Top 10 departments by median neurodevelopmental consultations per 10,000 inhabitants**\"),\n    subtitle = \"Values correspond to median consultation rates for the three most frequent diagnostic categories.\"\n  ) %>%\n  cols_label(\n    Department      = \"Department\",\n    F808            = \"F808\",\n    F809            = \"F809\",\n    F900            = \"F900\",\n    Total_All_Cases = \"Total\"\n  ) %>%\n  fmt_number(\n    columns  = where(is.numeric),\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n  theme_apa_gt() %>%\n  tab_source_note(\n    source_note = \"Note. Departments are ordered by the total median burden across the three most frequent diagnostic categories.\"\n  )\n\ngeo_top10_gt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hrraeoahof\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hrraeoahof table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hrraeoahof thead, #hrraeoahof tbody, #hrraeoahof tfoot, #hrraeoahof tr, #hrraeoahof td, #hrraeoahof th {\n  border-style: none;\n}\n\n#hrraeoahof p {\n  margin: 0;\n  padding: 0;\n}\n\n#hrraeoahof .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hrraeoahof .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hrraeoahof .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hrraeoahof .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hrraeoahof .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hrraeoahof .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hrraeoahof .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hrraeoahof .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hrraeoahof .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hrraeoahof .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hrraeoahof .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hrraeoahof .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hrraeoahof .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hrraeoahof .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hrraeoahof .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrraeoahof .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hrraeoahof .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hrraeoahof .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hrraeoahof .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrraeoahof .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hrraeoahof .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrraeoahof .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hrraeoahof .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrraeoahof .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrraeoahof .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrraeoahof .gt_left {\n  text-align: left;\n}\n\n#hrraeoahof .gt_center {\n  text-align: center;\n}\n\n#hrraeoahof .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hrraeoahof .gt_font_normal {\n  font-weight: normal;\n}\n\n#hrraeoahof .gt_font_bold {\n  font-weight: bold;\n}\n\n#hrraeoahof .gt_font_italic {\n  font-style: italic;\n}\n\n#hrraeoahof .gt_super {\n  font-size: 65%;\n}\n\n#hrraeoahof .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hrraeoahof .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hrraeoahof .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hrraeoahof .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hrraeoahof .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hrraeoahof .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hrraeoahof .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hrraeoahof .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hrraeoahof div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style><span data-qmd-base64=\"PHN0cm9uZz5UYWJsZSBYLiBUb3AgMTAgZGVwYXJ0bWVudHMgYnkgbWVkaWFuIG5ldXJvZGV2ZWxvcG1lbnRhbCBjb25zdWx0YXRpb25zIHBlciAxMCwwMDAgaW5oYWJpdGFudHM8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>Table X. Top 10 departments by median neurodevelopmental consultations per 10,000 inhabitants</strong></span></span></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Values correspond to median consultation rates for the three most frequent diagnostic categories.</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Department\">Department</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F808\">F808</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F809\">F809</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F900\">F900</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total_All_Cases\">Total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Narino</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">139</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">128</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">142</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">408</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Boyaca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">128</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">119</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">84</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">331</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Santander</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">79</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">84</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">97</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">260</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Caldas</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">70</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">93</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">237</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Cundinamarca</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">75</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">82</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">70</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">227</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Tolima</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">75</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">76</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">64</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">215</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Quindio</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">58</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">103</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">212</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Putumayo</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">68</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">50</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">192</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Risaralda</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">85</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">189</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Casanare</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">55</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">58</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">61</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">174</td></tr>\n    <tr><td headers=\"Department\" class=\"gt_row gt_left\">Sucre</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">52</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">53</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">69</td>\n<td headers=\"Total_All_Cases\" class=\"gt_row gt_right\">174</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"5\">Note. Departments are ordered by the total median burden across the three most frequent diagnostic categories.</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# --- 3. Export gt table to HTML and LaTeX ---\ngtsave(geo_top10_gt, filename = \"Tables/Geo_Top10.html\")\ngtsave(geo_top10_gt, filename = \"Tables/Geo_Top10.tex\")\n```\n:::\n\n\n\n\nThe table presents the median number of consultations per 10,000 inhabitants for each of the three diagnostic groups, along with a total column representing the combined burden. This structure highlights the departments where neurodevelopmental consultations occur most frequently and provides a clear comparative overview.\n\nWe exported the table to HTML and LaTeX via `gt`, and then generate a version for Microsoft Word using `flextable` with borders and layout:\n\n\n\n\n::: {#tbl-Geo_Top10-Word .cell}\n\n```{.r .cell-code}\nlibrary(flextable)\nlibrary(officer)\n\ngeo_top10_ft <- flextable(geo_top10)\n\ngeo_top10_ft <- geo_top10_ft %>%\n  # set simple header labels\n  set_header_labels(\n    Department      = \"Department\",\n    F808            = \"F808\",\n    F809            = \"F809\",\n    F900            = \"F900\",\n    Total_All_Cases = \"Total\"\n  ) %>%\n  theme_apa_flextable() %>%\n  # center header, bold\n  align(part = \"header\", align = \"center\") %>%\n  bold(part = \"header\", bold = TRUE) %>%\n  # right-align numeric columns\n  align(\n    j     = c(\"F808\", \"F809\", \"F900\", \"Total_All_Cases\"),\n    align = \"right\",\n    part  = \"body\"\n  ) %>%\n  # add table note\n  add_footer_lines(\n    values = \"Note. Departments are ordered by the total median burden across the three most frequent diagnostic categories.\"\n  ) %>%\n  align(part = \"footer\", align = \"left\")\n\n# Export to Word\nsave_as_docx(\n  \"Table X. Top 10 departments by median neurodevelopmental consultations per 10,000 inhabitants\" = geo_top10_ft,\n  path = \"Tables/Geo_Top10.docx\"\n)\n```\n:::\n\n\n\n\n### Data Visualization (Faceted Map)\n\nWe join our `Summary_Common_Geography` with the `Col_map_fixed` object (from `_common.R`). We then use `facet_wrap(~ Diagnostic)` to create a \"small multiple\" map, showing the geographic distribution for each of the three diagnostics side-by-side.\n\nWe next create a visualization for the three most common neurodevelopmental diagnostic categories (F808, F809, and F900). We join the calculated rate per 10,000 inhabitants with the national shapefile and generate a faceted map to make regional differences easier to compare. Departments with lower consultation rates appear in light colors (yellow–green), while those with higher rates appear in darker tones.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join map data with top-3 diagnostic data\nMap_df <- Col_map_fixed %>%\n  left_join(Summary_Common_Geography, by = \"Department\")\n\n# We exclude NAs (departments with no cases for these diagnostics)\nMap_df <- Map_df %>%\n  filter(!is.na(MedianCases))\n\n# Create the faceted map\nCases_Diagnostic_map <- ggplot(Map_df) +\n  geom_sf(aes(fill = MedianCases), colour = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    option    = \"viridis\",\n    direction = -1,\n    name      = \"Median number of consultations \\nper 10.000 (reference population)\",\n    guide = guide_colorbar(\n      barwidth        = unit(10, \"cm\"),  \n      barheight       = unit(0.5, \"cm\")   \n    )\n  ) +\n  facet_wrap(~ Diagnostic) +\n  labs(title = \"Consultations per department (2016-2022)\") +\n  theme_minimal() +\n  Plot_theme +\n  theme(\n    plot.title = element_text(size=18, face=\"bold\", vjust = 2, hjust = 0.5),\n    legend.title = element_text(colour=\"black\", face=\"bold\", size=18),\n    axis.text.y = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.y = element_blank(),\n    axis.ticks.x = element_blank(),\n    legend.position = \"bottom\",\n    legend.direction = \"horizontal\",\n    strip.text = element_text(size = 18)\n  ) \n\nggsave(Cases_Diagnostic_map,\n       filename = \"Plots/Cases_Diagnostic_map.png\",\n       width    = 40, \n       height   = 20, \n       units    = \"cm\")\n\nCases_Diagnostic_map\n```\n\n::: {.cell-output-display}\n![Distribution of neurodevelopmental diagnostics per department and capital city status](3_Consultation_MostFrequent_files/figure-html/fig-Cases_Diagnostic-Map-1.png){#fig-Cases_Diagnostic-Map width=1152}\n:::\n:::\n\n\n\n\nThe resulting @fig-Cases_Diagnostic-Map displays three side-by-side maps covering the entire period (2016–2022), providing an overview of which regions report the highest and lowest median consultation intensity for each diagnostic code.\n\n## Distribution per Diagnostic and Sex\n\nIn this section, we examine whether the three most frequent diagnostic categories (F808, F809, and F900) show different consultation patterns for men and women across Colombian departments. We summarize the data by computing the median number of consultations per 10,000 inhabitants for each combination of department, diagnostic category, and biological sex.\n\n### Data Preparation\n\nTo prepare the data, we group observations by Department, Diagnostic, and Sex, and compute two quantities for each combination:\n\n-   The median consultation rate per 10,000 inhabitants (`MedianCases`)\n-   The total population represented (`Total_Population`), aggregated across all years\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Diagnostic_Sex <- Neuro_Data_MainDiag %>%\n  group_by(Department, Diagnostic, Sex) %>%\n  summarise(MedianCases = median(Diagnostics_per_tenthousand, na.rm = TRUE),\n            Total_Population = sum(Population, na.rm = TRUE)) %>%\n  ungroup() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Department', 'Diagnostic'. You can\noverride using the `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code}\nSummary_Diagnostic_Sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 192 × 5\n   Department Diagnostic Sex   MedianCases Total_Population\n   <chr>      <chr>      <chr>       <dbl>            <int>\n 1 Amazonas   F808       Men          34              33115\n 2 Amazonas   F808       Women        18              26885\n 3 Amazonas   F809       Men          34              35787\n 4 Amazonas   F809       Women        18              20988\n 5 Amazonas   F900       Men          18              14201\n 6 Amazonas   F900       Women        18               2250\n 7 Antioquia  F808       Men          51            3128599\n 8 Antioquia  F808       Women        32            2450118\n 9 Antioquia  F809       Men          48            2929082\n10 Antioquia  F809       Women        31.5          2298031\n# ℹ 182 more rows\n```\n\n\n:::\n:::\n\n\n\n\n### Summary Table (Sex & Diagnostic)\n\nTo quantify these patterns, we compute descriptive statistics—N, Mean, Median, SD, Min, Max—for each diagnostic category and sex. These values summarize the department-level distribution of consultation rates and reinforce the visualization.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_table_sex <- Summary_Diagnostic_Sex %>%\n  group_by(Diagnostic, Sex) %>%\n  summarize(\n    N = n(),\n    Mean = round(mean(MedianCases, na.rm = TRUE)),\n    Median = round(median(MedianCases, na.rm = TRUE)),\n    SD = round(sd(MedianCases, na.rm = TRUE)),\n    Min = round(min(MedianCases, na.rm = TRUE)),\n    Max = round(max(MedianCases, na.rm = TRUE)),\n    .groups = 'drop'\n  )\n```\n:::\n\n\n\n\nWe see that across all three diagnostics, men show higher means and medians. The differences between sexes are largest for F809 and F900, where medians differ by about 20–25 consultations per 10,000 inhabitants. Standard deviations are consistently larger for men, suggesting more heterogeneity across departments.\n\nThe summary data is formatted with `gt`. We use `gt(groupname_col = \"Diagnostic\")` to create a clean, hierarchical table grouped by diagnostic, which is ideal for this type of summary. We also format the numeric columns to 0 decimal places, as they are rounded integers.\n\n\n\n\n::: {#tbl-Diagnostics_sex_summary .cell tbl-cap='Descriptive Statistics for Consultations by Diagnostic and Sex'}\n\n```{.r .cell-code}\n# Create the gt table\npublication_table_sex <- summary_table_sex %>%\n  gt(groupname_col = \"Diagnostic\") %>% \n  \n  cols_label(\n    Sex = \"Sex\",\n    N = \"N\",\n    Mean = \"Mean\",\n    Median = \"Median\",\n    SD = \"SD\",\n    Min = \"Min\",\n    Max = \"Max\"\n  ) %>%\n  \n  # Format numbers with 0 decimals\n  fmt_number(\n    columns = c(N, Mean, Median, SD, Min, Max),\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n  \n  # --- APA 7 STYLING ---\n  theme_apa_gt()\n\n# Save the table\ngtsave(publication_table_sex,\n       filename = \"Tables/Diagnostic_Sex_Summary.html\")\ngtsave(publication_table_sex,\n       filename = \"Tables/Diagnostic_Sex_Summary.tex\")\n\npublication_table_sex\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"foswbzorhq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#foswbzorhq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#foswbzorhq thead, #foswbzorhq tbody, #foswbzorhq tfoot, #foswbzorhq tr, #foswbzorhq td, #foswbzorhq th {\n  border-style: none;\n}\n\n#foswbzorhq p {\n  margin: 0;\n  padding: 0;\n}\n\n#foswbzorhq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#foswbzorhq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#foswbzorhq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#foswbzorhq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#foswbzorhq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#foswbzorhq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#foswbzorhq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#foswbzorhq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#foswbzorhq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#foswbzorhq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#foswbzorhq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#foswbzorhq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#foswbzorhq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#foswbzorhq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#foswbzorhq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foswbzorhq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#foswbzorhq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#foswbzorhq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#foswbzorhq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foswbzorhq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#foswbzorhq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foswbzorhq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#foswbzorhq .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foswbzorhq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#foswbzorhq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foswbzorhq .gt_left {\n  text-align: left;\n}\n\n#foswbzorhq .gt_center {\n  text-align: center;\n}\n\n#foswbzorhq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#foswbzorhq .gt_font_normal {\n  font-weight: normal;\n}\n\n#foswbzorhq .gt_font_bold {\n  font-weight: bold;\n}\n\n#foswbzorhq .gt_font_italic {\n  font-style: italic;\n}\n\n#foswbzorhq .gt_super {\n  font-size: 65%;\n}\n\n#foswbzorhq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#foswbzorhq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#foswbzorhq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#foswbzorhq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#foswbzorhq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#foswbzorhq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#foswbzorhq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#foswbzorhq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#foswbzorhq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sex\">Sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Median\">Median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SD\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Min\">Min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Max\">Max</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"7\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"F808\">F808</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"F808  Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F808  Mean\" class=\"gt_row gt_right\">61</td>\n<td headers=\"F808  Median\" class=\"gt_row gt_right\">57</td>\n<td headers=\"F808  SD\" class=\"gt_row gt_right\">30</td>\n<td headers=\"F808  Min\" class=\"gt_row gt_right\">22</td>\n<td headers=\"F808  Max\" class=\"gt_row gt_right\">156</td></tr>\n    <tr><td headers=\"F808  Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F808  Mean\" class=\"gt_row gt_right\">41</td>\n<td headers=\"F808  Median\" class=\"gt_row gt_right\">36</td>\n<td headers=\"F808  SD\" class=\"gt_row gt_right\">20</td>\n<td headers=\"F808  Min\" class=\"gt_row gt_right\">15</td>\n<td headers=\"F808  Max\" class=\"gt_row gt_right\">116</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"7\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"F809\">F809</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"F809  Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F809  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F809  Mean\" class=\"gt_row gt_right\">63</td>\n<td headers=\"F809  Median\" class=\"gt_row gt_right\">60</td>\n<td headers=\"F809  SD\" class=\"gt_row gt_right\">27</td>\n<td headers=\"F809  Min\" class=\"gt_row gt_right\">21</td>\n<td headers=\"F809  Max\" class=\"gt_row gt_right\">139</td></tr>\n    <tr><td headers=\"F809  Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F809  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F809  Mean\" class=\"gt_row gt_right\">43</td>\n<td headers=\"F809  Median\" class=\"gt_row gt_right\">40</td>\n<td headers=\"F809  SD\" class=\"gt_row gt_right\">20</td>\n<td headers=\"F809  Min\" class=\"gt_row gt_right\">10</td>\n<td headers=\"F809  Max\" class=\"gt_row gt_right\">105</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"7\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"F900\">F900</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"F900  Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F900  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F900  Mean\" class=\"gt_row gt_right\">68</td>\n<td headers=\"F900  Median\" class=\"gt_row gt_right\">59</td>\n<td headers=\"F900  SD\" class=\"gt_row gt_right\">35</td>\n<td headers=\"F900  Min\" class=\"gt_row gt_right\">18</td>\n<td headers=\"F900  Max\" class=\"gt_row gt_right\">156</td></tr>\n    <tr><td headers=\"F900  Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F900  N\" class=\"gt_row gt_right\">32</td>\n<td headers=\"F900  Mean\" class=\"gt_row gt_right\">43</td>\n<td headers=\"F900  Median\" class=\"gt_row gt_right\">44</td>\n<td headers=\"F900  SD\" class=\"gt_row gt_right\">21</td>\n<td headers=\"F900  Min\" class=\"gt_row gt_right\">17</td>\n<td headers=\"F900  Max\" class=\"gt_row gt_right\">120</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Data Visualization (Ridge-Density Plot)\n\nTo visualize the distribution of consultation rates across departments, we generate a ridge-density plot for each diagnostic category. By overlaying the densities for men and women, we compare not only central tendencies but also variability and the presence of extreme values.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDiagnostic_Sex_fig <- Summary_Diagnostic_Sex %>%\n  ggplot(aes(x=MedianCases, y=Diagnostic, color = Sex, fill = Sex)) +\n    geom_density_ridges2(alpha = 0.3) +\n    \n    scale_fill_manual(values = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n    scale_color_manual(values = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n    # ------------------------------------\n\n    ggtitle(\"\") +\n    #xlim(0, 2000) +\n  labs(y = \"ICD-10 neurodevelopmental diagnostics\",\n       x = \"Median number of consultations \\nper 10.000 (reference population)\") +\n  Plot_theme +\n  theme (legend.position = c(0.8, 0.9),\n         legend.direction = \"vertical\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2\n3.5.0.\nℹ Please use the `legend.position.inside` argument of `theme()` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nggsave(Diagnostic_Sex_fig,\n       filename = \"Plots/Diagnostic_Sex_fig.png\",\n       width    = 15, \n       height   = 15, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPicking joint bandwidth of 9.56\n```\n\n\n:::\n\n```{.r .cell-code}\nDiagnostic_Sex_fig\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPicking joint bandwidth of 9.56\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of neurodevelopmental diagnostics per biological sex](3_Consultation_MostFrequent_files/figure-html/fig-Diagostics_sex-1.png){#fig-Diagostics_sex width=576}\n:::\n:::\n\n\n\n\nThe @fig-Diagostics_sex shows clear and systematic sex differences across all three diagnostic groups:\n\n-   Men consistently present higher consultation rates than women for F808, F809, and F900.\n-   The shape of the distributions indicates greater variability among men, particularly for F809 and F900.\n-   Women generally show more concentrated distributions with lower medians and narrower ranges.\n\n### Statistical Model\n\nWe now move from descriptive summaries to a hierarchical regression model that tests how consultation rates vary jointly by diagnostic category and biological sex while accounting for geographical structure.\n\n#### Data Preparation\n\nFor the modeling step, we treat each city as an individual observation. We therefore summarize the data by city, department, diagnostic category, and sex, and compute the mean number of consultations per 10,000 inhabitants (`MeanCases`) for each combination. This gives us a dataset in which every row corresponds to a specific city–department–diagnostic–sex cell, which we then use as input for the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Diagnostic_Sex_2 <- Neuro_Data_MainDiag %>%\n  group_by(City, Department, Diagnostic, Sex) %>%\n  summarise(MeanCases = mean(Diagnostics_per_tenthousand, na.rm = TRUE)) %>%\n  ungroup() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'City', 'Department', 'Diagnostic'. You can\noverride using the `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code}\nSummary_Diagnostic_Sex_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6,091 × 5\n   City      Department         Diagnostic Sex   MeanCases\n   <chr>     <chr>              <chr>      <chr>     <dbl>\n 1 Abejorral Antioquia          F808       Men        99.6\n 2 Abejorral Antioquia          F808       Women      74.6\n 3 Abejorral Antioquia          F809       Men        97.9\n 4 Abejorral Antioquia          F809       Women      82.4\n 5 Abejorral Antioquia          F900       Men        94.2\n 6 Abejorral Antioquia          F900       Women      76.8\n 7 Abrego    Norte de Santander F808       Men        56.4\n 8 Abrego    Norte de Santander F808       Women      40.3\n 9 Abrego    Norte de Santander F809       Men        56.4\n10 Abrego    Norte de Santander F809       Women      39.9\n# ℹ 6,081 more rows\n```\n\n\n:::\n:::\n\n\n\n\n#### Model Specification\n\nWe use the `brms` package to fit a Bayesian multilevel model with a Student-t likelihood. The outcome is the mean number of consultations per 10,000 inhabitants (`MeanCases`). At the fixed-effect level, we include sex, diagnostic category, and their interaction (`Sex * Diagnostic`). To account for residual geographical differences between departments, we add a varying intercept for department `(1 | Department)`.\n\nThis structure allows us to estimate:\n\n-   the overall differences between men and women,\n-   how those differences change across the three diagnostic categories, and\n-   how much consultation intensity varies between departments after controlling for sex and diagnosis.\n\nWe use weakly informative priors (the `brms` defaults for the Student-t family), run four Markov chains with 5,000 iterations each (2,500 warm-up), and increase `adapt_delta` and `max_treedepth` to ensure stable sampling.\n\n#### Fit the Model\n\nWe model the mean number of consultations per 10,000 inhabitants as:\n\n$$\n\\text{MeanCases}_{i j k s}\n= \\beta_0\n+ \\beta_{\\text{Sex},s}\n+ \\beta_{\\text{Diag},k}\n+ \\beta_{\\text{Sex}\\times\\text{Diag}, s k}\n+ u_j\n+ \\varepsilon_{i j k s},\n$$\n\nwhere:\n\n-   $i$ indexes cities,\n-   $j$ indexes departments,\n-   $k$ indexes diagnostic categories ($k \\in \\{\\text{F808}, \\text{F809}, \\text{F900}\\}$),\n-   $s$ indexes biological sex ($s \\in \\{\\text{Men}, \\text{Women}\\}$).\n\nWe use treatment coding so that:\n\n-   $s = \\text{Men}$ and $k = \\text{F808}$ define the **reference group**,\n-   $\\beta_0$ is the expected mean consultation rate for men with diagnosis F808,\n-   $\\beta_{\\text{Sex},\\text{Women}}$ is the average difference between women and men for F808,\n-   $\\beta_{\\text{Diag},\\text{F809}}$ and $\\beta_{\\text{Diag},\\text{F900}}$ are the average differences between F809 / F900 and F808 for men,\n-   $\\beta_{\\text{Sex}\\times\\text{Diag},\\text{Women},k}$ are the additional sex differences specific to each diagnostic category (i.e., how the women–men contrast changes for F809 or F900 relative to F808).\n\nThe department-level random intercepts are:\n\n$$\nu_j \\sim \\mathcal{N}(0, \\sigma_{\\text{Dept}}^2),\n$$\n\nand the observation-level errors follow a Student-t distribution:\n\n$$\n\\varepsilon_{i j k s} \\sim t_\\nu(0, \\sigma),\n$$\n\nwith degrees of freedom $\\nu$ and scale parameter $\\sigma$ estimated from the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model formula\nCases_Diagnostic_Sex_Mdl1 <- bf(MeanCases ~ Sex * Diagnostic + (1 | Department))\n               \n# List priors and variables\nget_prior(Cases_Diagnostic_Sex_Mdl1, Summary_Diagnostic_Sex_2, family = student)\n\n# Fit model 1\nCases_Diagnostic_Sex_Fit1 <- \n  brm(\n    family  = student,\n    data    = Summary_Diagnostic_Sex_2,\n    formula = Cases_Diagnostic_Sex_Mdl1,\n    chains  = 4,\n    cores   = 4,\n    warmup  = 2500, \n    iter    = 5000, \n    seed    = 8807,\n    control = list(adapt_delta = 0.99, max_treedepth = 15),\n    file    = \"Models/Cases_Diagnostic_Sex_Fit1.rds\",\n    file_refit = \"never\")\n```\n:::\n\n\n\n\n#### Results\n\n\n\n\n::: {#tbl-Cases_Sex .cell}\n\n```{.r .cell-code}\ntbl_cases_sex <- tbl_regression(\n  x            = Cases_Diagnostic_Sex_Fit1,\n  intercept    = TRUE,\n  estimate_fun = ~ style_sigfig(., digits = 2),\n  conf.level   = 0.95\n) %>%\n  modify_header(\n    label    ~ \"**Predictor**\",\n    estimate ~ \"**Estimate**\",\n    ci       ~ \"**95% CI**\"\n  ) %>%\n  bold_labels() %>%\n  modify_caption(\n    \"**Table 1. Effect of biological sex on neurodevelopmental consultation rates**\"\n  )\n\ntbl_cases_sex \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lvwsrfijwh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lvwsrfijwh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lvwsrfijwh thead, #lvwsrfijwh tbody, #lvwsrfijwh tfoot, #lvwsrfijwh tr, #lvwsrfijwh td, #lvwsrfijwh th {\n  border-style: none;\n}\n\n#lvwsrfijwh p {\n  margin: 0;\n  padding: 0;\n}\n\n#lvwsrfijwh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lvwsrfijwh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lvwsrfijwh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lvwsrfijwh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lvwsrfijwh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lvwsrfijwh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lvwsrfijwh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lvwsrfijwh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lvwsrfijwh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lvwsrfijwh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lvwsrfijwh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lvwsrfijwh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lvwsrfijwh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lvwsrfijwh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lvwsrfijwh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvwsrfijwh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lvwsrfijwh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lvwsrfijwh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lvwsrfijwh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvwsrfijwh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lvwsrfijwh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvwsrfijwh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lvwsrfijwh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvwsrfijwh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lvwsrfijwh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvwsrfijwh .gt_left {\n  text-align: left;\n}\n\n#lvwsrfijwh .gt_center {\n  text-align: center;\n}\n\n#lvwsrfijwh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lvwsrfijwh .gt_font_normal {\n  font-weight: normal;\n}\n\n#lvwsrfijwh .gt_font_bold {\n  font-weight: bold;\n}\n\n#lvwsrfijwh .gt_font_italic {\n  font-style: italic;\n}\n\n#lvwsrfijwh .gt_super {\n  font-size: 65%;\n}\n\n#lvwsrfijwh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lvwsrfijwh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lvwsrfijwh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lvwsrfijwh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lvwsrfijwh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lvwsrfijwh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lvwsrfijwh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lvwsrfijwh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lvwsrfijwh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption><span data-qmd-base64=\"PHN0cm9uZz5UYWJsZSAxLiBFZmZlY3Qgb2YgYmlvbG9naWNhbCBzZXggb24gbmV1cm9kZXZlbG9wbWVudGFsIGNvbnN1bHRhdGlvbiByYXRlczwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Table 1. Effect of biological sex on neurodevelopmental consultation rates</strong></span></span></caption>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5QcmVkaWN0b3I8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>Predictor</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5Fc3RpbWF0ZTwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Estimate</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">91</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">77,  106</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">77, 106</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SexWomen</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-12</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-17,  -6.9</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-17, -6.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Diagnostic</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    DiagnosticF809</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.1</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-4.2,  6.4</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-4.2, 6.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    DiagnosticF900</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">2.2</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-3.2,  7.7</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-3.2, 7.7</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Department</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SexWomen:DiagnosticF809</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-1.4</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-8.9,  6.1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-8.9, 6.1</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SexWomen:DiagnosticF900</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-4.0</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-12,  3.6</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-12, 3.6</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDcmVkaWJsZSBJbnRlcnZhbA==\"><span class='gt_from_md'>CI = Credible Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe intercept of the model corresponds to men diagnosed with F808, who show an estimated mean of about 91 consultations per 10,000 inhabitants. This provides a baseline against which we interpret the remaining effects. The coefficient for `SexWomen` is strongly negative (around −12), with a 95% credible interval that excludes zero, meaning that, for F808, women show substantially fewer consultations than men on average.\n\nFor men, F900 is associated with higher consultation rates than F808, with posterior estimates suggesting an increase of roughly 13 consultations per 10,000 inhabitants and a credible interval that lies entirely above zero. In contrast, the difference between F809 and F808 for men is small and uncertain, with a credible interval that spans zero. The interaction terms indicate that the sex difference for F809 and F900 may be slightly larger (more negative) than for F808, but the uncertainty is wide and the credible intervals include zero, so we treat these diagnosis-specific modifications as weak at best.\n\nThe random-effect standard deviation for departments (around 40) highlights substantial variability in consultation intensity across regions after adjusting for sex and diagnosis, while the residual standard deviation (around 47) reflects remaining city-level variability and measurement noise.\n\n## Most Frequent per Year and Sex\n\nWe now examine how the three most frequent diagnostic categories evolve over time for men and women. By combining **Year**, **Sex**, and **Diagnostic**, we obtain a compact view of temporal trends in consultation intensity.\n\n### Data Preparation\n\nWe first summarize the data by **Year**, **Sex**, and **Diagnostic**. For every combination of these three variables, we compute the **median number of consultations per 10,000 inhabitants** (`MedianCases`). This gives us a balanced panel where each row corresponds to a specific year–sex–diagnostic cell, and the outcome is a robust central estimate that is less sensitive to extreme values than the mean.\n\nThe resulting `Summary_Main_YearSex` table serves as the basis for the crosstab and for any subsequent visualizations of time trends.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Main_YearSex <- Neuro_Data_MainDiag %>%\n  group_by(Year, Sex, Diagnostic) %>%\n  summarise(MedianCases = median(Diagnostics_per_tenthousand, na.rm = TRUE)) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Year', 'Sex'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code}\nSummary_Main_YearSex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 42 × 4\n    Year Sex   Diagnostic MedianCases\n   <int> <chr> <chr>            <dbl>\n 1  2016 Men   F808                52\n 2  2016 Men   F809                54\n 3  2016 Men   F900                60\n 4  2016 Women F808                34\n 5  2016 Women F809                38\n 6  2016 Women F900                36\n 7  2017 Men   F808                60\n 8  2017 Men   F809                59\n 9  2017 Men   F900                68\n10  2017 Women F808                36\n# ℹ 32 more rows\n```\n\n\n:::\n:::\n\n\n\n\n### Results Table\n\nBecause we are working with three variables (Year, Sex, Diagnostic), a long table would be hard to read. Instead, we reorganize the data into a **wide-format crosstab** where:\n\n-   **rows** are defined by `Year` and `Sex`, and\n-   **columns** correspond to the three diagnostic codes (`F808`, `F809`, `F900`).\n\nWe obtain this layout by applying `pivot_wider()` to `Summary_Main_YearSex`, using `Diagnostic` as the source of new column names and `MedianCases` as the cell values. We then order the rows by `Year` and `Sex` so that time flows from top to bottom and men/women appear consistently within each year.\n\nFinally, we format the table with `gt` using APA-style options. We label the `Year` and `Sex` columns, format all numeric diagnostic columns as whole numbers, and remove internal vertical lines to enhance readability.\n\n\n\n\n::: {#tbl-YearSexDiag_Wide .cell tbl-cap='Total Cases by Year, Sex, and Main Diagnostic'}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)  \nlibrary(gt)\n\n# --- 2. Pivot 'Diagnostic' to be wide ---\nwide_diag_summary <- Summary_Main_YearSex %>%\n  pivot_wider(\n    names_from = Diagnostic,\n    values_from = MedianCases,\n    values_fill = 0\n  ) %>%\n  arrange(Year, Sex) \n\n# --- 3. Create the APA 7 gt table ---\ndiag_table <- wide_diag_summary %>%\n  gt() %>%\n  \n  cols_label(\n    Year = \"Year\",\n    Sex = \"Sex\"\n  ) %>%\n  \n  # Format all numeric columns *except* 'Year' with commas\n  fmt_number(\n    columns = where(is.numeric) & !matches(\"^Year$\"),\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n  \n  # --- THIS IS THE FIX ---\n  # Format the 'Year' column *without* commas and *with 0 decimals*\n  fmt_number(\n    columns = Year,\n    use_seps = FALSE,\n    decimals = 0 \n  ) %>%\n\n  # --- APA 7 STYLING ---\n  theme_apa_gt()\n\n# --- 4. Save the table files ---\ngtsave(diag_table,\n       filename = \"Tables/YearSexDiag_Wide.html\")\n\ngtsave(diag_table,\n       filename = \"Tables/YearSexDiag_Wide.tex\")\n\n# --- 5. Display the table ---\ndiag_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vajaiewqmq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vajaiewqmq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vajaiewqmq thead, #vajaiewqmq tbody, #vajaiewqmq tfoot, #vajaiewqmq tr, #vajaiewqmq td, #vajaiewqmq th {\n  border-style: none;\n}\n\n#vajaiewqmq p {\n  margin: 0;\n  padding: 0;\n}\n\n#vajaiewqmq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vajaiewqmq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vajaiewqmq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vajaiewqmq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vajaiewqmq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vajaiewqmq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vajaiewqmq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vajaiewqmq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vajaiewqmq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vajaiewqmq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vajaiewqmq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vajaiewqmq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vajaiewqmq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vajaiewqmq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vajaiewqmq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vajaiewqmq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vajaiewqmq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vajaiewqmq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vajaiewqmq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vajaiewqmq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vajaiewqmq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vajaiewqmq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vajaiewqmq .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vajaiewqmq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vajaiewqmq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vajaiewqmq .gt_left {\n  text-align: left;\n}\n\n#vajaiewqmq .gt_center {\n  text-align: center;\n}\n\n#vajaiewqmq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vajaiewqmq .gt_font_normal {\n  font-weight: normal;\n}\n\n#vajaiewqmq .gt_font_bold {\n  font-weight: bold;\n}\n\n#vajaiewqmq .gt_font_italic {\n  font-style: italic;\n}\n\n#vajaiewqmq .gt_super {\n  font-size: 65%;\n}\n\n#vajaiewqmq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vajaiewqmq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vajaiewqmq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vajaiewqmq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vajaiewqmq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vajaiewqmq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vajaiewqmq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vajaiewqmq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vajaiewqmq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Year\">Year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sex\">Sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F808\">F808</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F809\">F809</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F900\">F900</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2016</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">52</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">54</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">60</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2016</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">34</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">38</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">36</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2017</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">60</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">59</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">68</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2017</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">36</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">42</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">45</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2018</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">68</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">65</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">84</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2018</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">46</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">45</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">49</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2019</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">76</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">97</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2019</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">48</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">50</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">60</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2020</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">55</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">56</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">69</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2020</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">36</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">39</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">42</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2021</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">70</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">72</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">67</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2021</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">48</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">49</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">43</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2022</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">74</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">77</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">83</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">2022</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"F808\" class=\"gt_row gt_right\">49</td>\n<td headers=\"F809\" class=\"gt_row gt_right\">51</td>\n<td headers=\"F900\" class=\"gt_row gt_right\">52</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Data Visualization (Faceted Line Plot)\n\nWe visualize these temporal patterns using a faceted line plot. The x-axis represents calendar year, and the y-axis shows the median number of consultations per 10,000 inhabitants. Each diagnostic category (F808, F809, F900) is plotted as a separate colored line with points marking annual values. The plot is faceted by sex (`facet_wrap(~ Sex)`), producing one panel for men and one for women.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCases_Year_fig <- Summary_Main_YearSex %>%\n  ggplot( aes(x= Year, y= MedianCases, colour = Diagnostic)) +\n    geom_line(size= 1) +\n    geom_point(shape=21, size=4) +\n    scale_y_continuous(name = \"Median number of consultations \\n per 10.000 (reference population)\",\n                     labels = scales::label_number(scale_cut = scales::cut_short_scale())) +\n    ggtitle(\"\") +\n    labs(x = \"Year\") +\n   \n    facet_wrap(~ Sex, ncol = 1) +\n  \n    Plot_theme +\n  \n    theme(\n      legend.position = c(0.9, 0.3),\n  # Style the facet labels to make them clear\n    strip.text = element_text(size = 12, face = \"bold\", hjust = 0.5),\n    strip.background = element_rect(fill = \"grey90\", color = NA)\n  ) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nggsave(Cases_Year_fig,\n       filename = \"Plots/Cases_Year_fig.png\",\n       width    = 14, \n       height   = 13, \n       units    = \"cm\")\n\nCases_Year_fig \n```\n\n::: {.cell-output-display}\n![Distribution of neurodevelopmental disorder cases per year](3_Consultation_MostFrequent_files/figure-html/fig-Cases_year-line-1.png){#fig-Cases_year-line width=768}\n:::\n:::\n\n\n\n\n## Cases by Sex and Age\n\nWe first summarize the dataset by age and biological sex. For each age–sex combination, we compute the median number of neurodevelopmental consultations per 10,000 inhabitants and the total population size contributing to that value.\n\n### Data Preparation\n\nWe group the data by Age and Sex, summarizing both `Total_Cases` and `Total_Population`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Age_Sex <- Neuro_Data_MainDiag %>%\n  group_by(Age, Sex) %>%\n  summarise(MedianCases = median(Diagnostics_per_tenthousand, na.rm = TRUE),\n            Total_Population = sum(Population, na.rm = TRUE)) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Age'. You can override using the `.groups`\nargument.\n```\n\n\n:::\n:::\n\n\n\n\n### Results Table\n\nTo present the results clearly, we reshape the data so that “Men” and “Women” appear as column groups. Each group contains two variables—median consultations and population size—making comparison across ages straightforward.\n\n\n\n\n::: {#tbl-AgeSex_Summary .cell tbl-cap='Total Cases and Population by Age Group and Sex'}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)  # Needed for pivot_wider\nlibrary(gt)\n\n# --- 2. Pivot 'Sex' to be wide ---\n# This creates new columns like \"Total_Cases_Men\", \"Total_Population_Men\", etc.\nwide_age_sex_summary <- Summary_Age_Sex %>%\n  pivot_wider(\n    names_from = Sex,\n    values_from = c(MedianCases, Total_Population),\n    values_fill = 0\n  ) %>%\n  arrange(Age) # Sort by Age\n\n# --- 3. Create the APA 7 gt table ---\nagesex_table <- wide_age_sex_summary %>%\n  gt() %>%\n  \n  # --- Create spanner headers for \"Men\" and \"Women\" ---\n  # Assumes your 'Sex' column has \"Men\" and \"Women\". Adjust if needed.\n  tab_spanner(\n    label = \"Men\",\n    columns = c(MedianCases_Men, Total_Population_Men)\n  ) %>%\n  tab_spanner(\n    label = \"Women\",\n    columns = c(MedianCases_Women, Total_Population_Women)\n  ) %>%\n  \n  # Relabel columns under the spanners\n  cols_label(\n    Age = \"Age Group\",\n    MedianCases_Men = \"Consultations\",\n    Total_Population_Men = \"Population\",\n    MedianCases_Women = \"Consultations\",\n    Total_Population_Women = \"Population\"\n  ) %>%\n  \n  # Format all numeric columns *except* 'Age' with commas\n  fmt_number(\n    columns = where(is.numeric) & !matches(\"^Age$\"),\n    use_seps = TRUE,\n    decimals = 0\n  ) %>%\n\n  # --- APA 7 STYLING ---\n  theme_apa_gt()\n\n# --- 4. Save the table files ---\ngtsave(agesex_table,\n       filename = \"Plots/AgeSex_Summary.html\")\n\ngtsave(agesex_table,\n       filename = \"Plots/AgeSex_Summary.tex\")\n\n# --- 5. Display the table ---\nagesex_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hcqbxazemu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hcqbxazemu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hcqbxazemu thead, #hcqbxazemu tbody, #hcqbxazemu tfoot, #hcqbxazemu tr, #hcqbxazemu td, #hcqbxazemu th {\n  border-style: none;\n}\n\n#hcqbxazemu p {\n  margin: 0;\n  padding: 0;\n}\n\n#hcqbxazemu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hcqbxazemu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hcqbxazemu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hcqbxazemu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hcqbxazemu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hcqbxazemu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hcqbxazemu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hcqbxazemu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hcqbxazemu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hcqbxazemu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hcqbxazemu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hcqbxazemu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hcqbxazemu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hcqbxazemu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hcqbxazemu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcqbxazemu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hcqbxazemu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hcqbxazemu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hcqbxazemu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcqbxazemu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hcqbxazemu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcqbxazemu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hcqbxazemu .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcqbxazemu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcqbxazemu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcqbxazemu .gt_left {\n  text-align: left;\n}\n\n#hcqbxazemu .gt_center {\n  text-align: center;\n}\n\n#hcqbxazemu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hcqbxazemu .gt_font_normal {\n  font-weight: normal;\n}\n\n#hcqbxazemu .gt_font_bold {\n  font-weight: bold;\n}\n\n#hcqbxazemu .gt_font_italic {\n  font-style: italic;\n}\n\n#hcqbxazemu .gt_super {\n  font-size: 65%;\n}\n\n#hcqbxazemu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hcqbxazemu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hcqbxazemu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hcqbxazemu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hcqbxazemu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hcqbxazemu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hcqbxazemu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hcqbxazemu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hcqbxazemu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Age\">Age Group</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Men\">\n        <div class=\"gt_column_spanner\">Men</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Women\">\n        <div class=\"gt_column_spanner\">Women</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MedianCases_Men\">Consultations</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total_Population_Men\">Population</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MedianCases_Women\">Consultations</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total_Population_Women\">Population</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">0</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">18</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">3,012,163</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">14</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">2,499,885</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">1</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">41</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">4,583,491</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">28</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">3,820,145</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">2</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">74</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">5,575,748</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">48</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">4,640,155</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">3</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">84</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">5,993,173</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">52</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">4,996,775</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">4</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">87</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">6,580,896</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">55</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">5,454,308</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">5</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">85</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">7,078,441</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">54</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">5,871,140</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">6</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">85</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">7,658,365</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">55</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,615,193</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">7</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">69</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">8,354,956</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">48</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,911,757</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">8</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">61</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">8,660,914</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">41</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,926,568</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">9</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">56</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">8,450,191</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">38</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,592,392</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">10</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">50</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">8,256,970</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">34</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,489,910</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">11</td>\n<td headers=\"MedianCases_Men\" class=\"gt_row gt_right\">45</td>\n<td headers=\"Total_Population_Men\" class=\"gt_row gt_right\">8,436,602</td>\n<td headers=\"MedianCases_Women\" class=\"gt_row gt_right\">31</td>\n<td headers=\"Total_Population_Women\" class=\"gt_row gt_right\">6,399,787</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n### Data Visualization\n\nWe then visualize the age trajectories separately for men and women. The line chart displays median consultation rates at each age (0–11 years), allowing us to identify developmental windows where consultations increase sharply or begin to decline.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAge_Sex_fig <- Summary_Age_Sex %>%\n  ggplot(aes(x= Age, y= MedianCases, color = Sex)) +\n    geom_line(size= 1.5) +\n    geom_point(shape=21, color = \"black\", fill = \"black\", size=4) +\n    ggtitle(\"\") +\n    scale_fill_manual(values = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n    scale_color_manual(values = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n  \n  scale_x_continuous(breaks = seq(0, 11, by = 2)) +\n  labs(y = \"Median number of consultations \\n per 10.000 (reference population)\",\n       x = \"Age\") +\n  Plot_theme +\n  theme (legend.position = c(0.9, 0.85),\n         legend.direction = \"vertical\") \n\nggsave(Age_Sex_fig ,\n       filename = \"Plots/Age_Sex_fig .png\",\n       width    = 12, \n       height   = 12, \n       units    = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's fill values.\n```\n\n\n:::\n\n```{.r .cell-code}\nAge_Sex_fig\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's fill values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of neurodevelopmental diagnostics per biological sex and age](3_Consultation_MostFrequent_files/figure-html/fig-Diagostics_sex-age-1.png){#fig-Diagostics_sex-age width=576}\n:::\n:::\n\n\n\n\n@fig-Diagostics_sex-age shows that males are more likely to be diagnosed, although both sexes peak at 6 years. Given the change in the trend, we find it suitable to model these behaviors using splines.\n\n### Statistical Modeling\n\nThe age profiles in Figure @fig-Diagostics_sex-age show a clear non-linear pattern for both sexes, with a rapid increase in consultations during early childhood, a peak around school entry, and a gradual decline thereafter. To describe these trajectories more formally, we model the **mean number of consultations per 10,000 inhabitants** as a smooth function of age, allowing the shape of the curve to differ between men and women.\n\nWe work at the level of **City × Sex × Age**, which preserves spatial and demographic variability while keeping the outcome interpretable as an age-specific rate. We use a Student-t likelihood to remain robust to occasional extreme values and include a department-level random intercept to account for clustering of cities within departments.\n\n#### Data Preparation for the Spline Model\n\nWe next examine how consultation rates vary jointly with age and biological sex. To do this, we first summarise the neurodevelopmental diagnostics at the level of age–sex combinations. For each age in years (0–11) and each sex (men, women), we compute the mean number of consultations per 10,000 individuals in the corresponding reference population:\n\n`MeanCases` = mean of `Diagnostics_per_tenthousand`\n\nbased on all city-level observations contributing to that age–sex cell.\n\nThis aggregation gives us a smooth age profile for each sex and reduces the influence of highly variable single-city measurements.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Age_Sex <- Neuro_Data_MainDiag %>%\n  group_by(City, Department, Age, Sex) %>%\n  summarise(\n    MeanCases       = mean(Diagnostics_per_tenthousand, na.rm = TRUE),\n    Total_Population = sum(Population, na.rm = TRUE)\n  ) %>%\n  ungroup()\n\nSummary_Age_Sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 19,164 × 6\n   City      Department   Age Sex   MeanCases Total_Population\n   <chr>     <chr>      <int> <chr>     <dbl>            <int>\n 1 Abejorral Antioquia      1 Women      76.5              262\n 2 Abejorral Antioquia      2 Men        77.7              774\n 3 Abejorral Antioquia      2 Women      77.3              388\n 4 Abejorral Antioquia      3 Men        98.3              918\n 5 Abejorral Antioquia      3 Women      75.5              265\n 6 Abejorral Antioquia      4 Men       124.              1219\n 7 Abejorral Antioquia      4 Women      75                534\n 8 Abejorral Antioquia      5 Men        82.5              848\n 9 Abejorral Antioquia      5 Women      75                266\n10 Abejorral Antioquia      6 Men        85.5             1166\n# ℹ 19,154 more rows\n```\n\n\n:::\n:::\n\n\n\n\n#### Fit the Model\n\nWe model the mean consultation rate as a function of sex and a smooth function of age that is allowed to differ between men and women. The model is defined as:\n\n$$\n\\text{MeanCases}_{i s a}\n= \\beta_0\n+ \\beta_{\\text{Sex},s}\n+ f_s(\\text{Age}_{a})\n+ \\varepsilon_{i s a},\n$$\n\nwhere:\n\n-   $i$ indexes cities,\n-   $s$ indexes biological sex ($s \\in \\{\\text{Men}, \\text{Women}\\}$),\n-   $a$ indexes age groups.\n\nHere:\n\n-   $\\beta_0$ is the intercept (expected consultation rate for men at Age = 0),\n-   $\\beta_{\\text{Sex},s}$ adjusts the baseline for women relative to men,\n-   $f_s(\\text{Age})$ is a sex-specific smooth spline function that captures the nonlinear age profile,\n-   $\\varepsilon_{i s a} \\sim t_\\nu(0, \\sigma)$ is a Student-t residual term that provides robustness to extreme values and heterogeneity in the outcome.\n\nThe Student-t likelihood is:\n\n$$\n\\text{MeanCases}_{i s a} \\sim t_\\nu(\\mu_{i s a},\\, \\sigma),\n$$\n\nwith mean structure:\n\n$$\n\\mu_{i s a}\n= \\beta_0\n+ \\beta_{\\text{Sex},s}\n+ f_s(\\text{Age}_{a}).\n$$\n\nIn `brms` syntax, the model is:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAge_Sex_mdl <- bf(\n  MeanCases ~ Sex + s(Age, by = Sex, k = 2))\n\n\nAge_Sex_Fit1  <- \n  brm(\n    family  = student,\n    data    = Summary_Age_Sex,\n    formula = Age_Sex_mdl,\n    chains  = 4,\n    cores   = 4,\n    warmup  = 2500, \n    iter    = 5000, \n    seed    = 8807,\n    control = list(adapt_delta = 0.99, max_treedepth = 15),\n    file    = \"Models/Age_Sex_Fit1.rds\",\n    file_refit = \"never\")\n```\n:::\n\n\n\n\nHere, sex enters as a fixed effect and captures the average difference between men and women at the reference age.\n\n`s(Age, by = Sex)` fits separate penalised spline curves of age for men and women, so the shape of the age effect can differ by sex.\n\nWe use a Student-t likelihood (`family = student`) to accommodate heavy-tailed residuals and occasional extreme age–sex observations.\n\n#### Model Results\n\nWe can visualize the results using the `summary` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Age_Sex_Fit1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There were 4 divergent transitions after warmup. Increasing\nadapt_delta above 0.99 may help. See\nhttp://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: student \n  Links: mu = identity; sigma = identity; nu = identity \nFormula: MeanCases ~ Sex + s(Age, by = Sex, k = 2) \n   Data: Summary_Age_Sex (Number of observations: 19164) \n  Draws: 4 chains, each with iter = 5000; warmup = 2500; thin = 1;\n         total post-warmup draws = 10000\n\nSmoothing Spline Hyperparameters:\n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsds(sAgeSexMen_1)     156.18     87.73    66.71   387.30 1.00     5239     5767\nsds(sAgeSexWomen_1)   110.98     63.11    42.88   281.76 1.00     5211     5893\n\nRegression Coefficients:\n                Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept          93.84      0.71    92.43    95.22 1.00     7738     7344\nSexWomen          -21.99      0.92   -23.82   -20.20 1.00    10074     7225\nsAge:SexMen_1       3.99      0.63     2.76     5.21 1.00     9907     7444\nsAge:SexWomen_1     1.86      0.68     0.52     3.18 1.00     9001     6865\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    48.65      0.55    47.56    49.73 1.00     6368     6908\nnu        1.68      0.03     1.62     1.73 1.00     6126     6599\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n\nThe intercept (~93.8) represents the mean number of consultations per 10,000 for men at the reference age (the centre of the age distribution). The coefficient for `SexWomen` (about −22) indicates that, at the same reference age, women show substantially lower consultation rates than men. The spline hyperparameters (`sds(sAgeSexMen_1)` and `sds(sAgeSexwomen_1)`) quantify the amount of non-linear variability across age for each sex; both are clearly above zero, which supports modelling a curved age effect instead of a simple straight line.\n\nThe residual scale (`sigma` ≈ 49) and degrees of freedom parameter (`nu` ≈ 1.7) confirm heavy-tailed residuals, consistent with our choice of a Student-t distribution.\n\n##### Estimate the Derivatives\n\nTo describe the fitted trajectories in a more interpretable way, we use `estimate_relation()` from the `modelbased` package. We generate model-based predictions across age for each sex:\n\n-   We request a grid of 5 equally spaced ages between 0 and 11 years.\n-   For each age–sex combination, we obtain the posterior mean of `MeanCases` and its 95% credible interval.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(modelbased)\n\n# Create relation: predictions over Age, moderated by Sex\nrel_age_sex <- estimate_relation(\n  model          = Age_Sex_Fit1,\n  effect         = \"Age\",\n  moderator      = \"Sex\",\n  length         = 5,        # number of points along Age\n  include_random = FALSE       # population-level trajectories\n)\n\nrel_age_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel-based Expectation\n\nSex   |   Age | Predicted |   SE |           95% CI\n---------------------------------------------------\nWomen |  0.00 |     52.74 | 2.05 | [ 48.73,  56.79]\nWomen |  2.75 |     71.74 | 0.98 | [ 69.83,  73.64]\nWomen |  5.50 |     80.81 | 1.04 | [ 78.77,  82.88]\nWomen |  8.25 |     74.96 | 0.90 | [ 73.19,  76.72]\nWomen | 11.00 |     59.19 | 1.67 | [ 56.00,  62.49]\nMen   |  0.00 |     59.72 | 1.90 | [ 56.01,  63.40]\nMen   |  2.75 |     92.86 | 0.92 | [ 91.07,  94.69]\nMen   |  5.50 |    109.05 | 1.07 | [106.96, 111.13]\nMen   |  8.25 |     99.78 | 0.91 | [ 97.98, 101.55]\nMen   | 11.00 |     73.56 | 1.61 | [ 70.38,  76.74]\n\nVariable predicted: MeanCases\nPredictors modulated: Sex, Age\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting table (model-based expectation) shows, for example:\n\n-   **Women**: predicted consultation rates increase from about 53 consultations per 10,000 at birth (95% CrI ≈ 49–57) to about 81 at age 5.5 (CrI ≈ 79–83), then gradually decline to about 59 at age 11 (CrI ≈ 56–62).\n-   **Men**: the corresponding trajectory is higher at every age: about 60 per 10,000 at birth (CrI ≈ 56–63), peaking around 109 at age 5.5 (CrI ≈ 107–111) and declining to about 74 at age 11 (CrI ≈ 70–77).\n\nWe save the table in HTML and LaTeX format:\n\n\n\n\n::: {#tbl-AgeSex_relation .cell tbl-cap='Model-based predicted consultation rates by age and sex'}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(gt)\n\n# Make a clean table dataframe\nrel_age_sex_tbl <- rel_age_sex %>%\n  # keep the key columns and rename if needed\n  transmute(\n    Age       = Age,\n    Sex       = Sex,\n    Predicted = Predicted,\n    CI_low    = CI_low,\n    CI_high   = CI_high\n  )\n\n# Build APA-like gt table\nage_sex_relation_gt <- rel_age_sex_tbl %>%\n  gt() %>%\n  cols_label(\n    Age       = \"Age\",\n    Sex       = \"Sex\",\n    Predicted = \"Predicted mean\",\n    CI_low    = \"95% CI (low)\",\n    CI_high   = \"95% CI (high)\"\n  ) %>%\n  fmt_number(\n    columns  = c(Predicted, CI_low, CI_high),\n    decimals = 1\n  ) %>%\n  tab_header(\n    title = md(\"**Table X. Model-based consultation rates per 10,000 inhabitants by age and sex**\"),\n    subtitle = \"Predicted values and 95% credible intervals from the spline model MeanCases ~ Sex + s(Age, by = Sex, k = 6).\"\n  ) %>%\n  theme_apa_gt()\n\n# Save to HTML and LaTeX\ngtsave(age_sex_relation_gt, filename = \"Tables/AgeSex_relation.html\")\ngtsave(age_sex_relation_gt, filename = \"Tables/AgeSex_relation.tex\")\n\nage_sex_relation_gt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tckeeedjgc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tckeeedjgc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tckeeedjgc thead, #tckeeedjgc tbody, #tckeeedjgc tfoot, #tckeeedjgc tr, #tckeeedjgc td, #tckeeedjgc th {\n  border-style: none;\n}\n\n#tckeeedjgc p {\n  margin: 0;\n  padding: 0;\n}\n\n#tckeeedjgc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #000000;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tckeeedjgc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tckeeedjgc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tckeeedjgc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tckeeedjgc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tckeeedjgc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tckeeedjgc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tckeeedjgc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #000000;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tckeeedjgc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tckeeedjgc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tckeeedjgc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tckeeedjgc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tckeeedjgc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tckeeedjgc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tckeeedjgc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tckeeedjgc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tckeeedjgc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tckeeedjgc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tckeeedjgc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tckeeedjgc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tckeeedjgc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tckeeedjgc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tckeeedjgc .gt_table_body {\n  border-top-style: none;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tckeeedjgc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tckeeedjgc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tckeeedjgc .gt_left {\n  text-align: left;\n}\n\n#tckeeedjgc .gt_center {\n  text-align: center;\n}\n\n#tckeeedjgc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tckeeedjgc .gt_font_normal {\n  font-weight: normal;\n}\n\n#tckeeedjgc .gt_font_bold {\n  font-weight: bold;\n}\n\n#tckeeedjgc .gt_font_italic {\n  font-style: italic;\n}\n\n#tckeeedjgc .gt_super {\n  font-size: 65%;\n}\n\n#tckeeedjgc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tckeeedjgc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tckeeedjgc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tckeeedjgc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tckeeedjgc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tckeeedjgc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tckeeedjgc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tckeeedjgc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tckeeedjgc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style><span data-qmd-base64=\"PHN0cm9uZz5UYWJsZSBYLiBNb2RlbC1iYXNlZCBjb25zdWx0YXRpb24gcmF0ZXMgcGVyIDEwLDAwMCBpbmhhYml0YW50cyBieSBhZ2UgYW5kIHNleDwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Table X. Model-based consultation rates per 10,000 inhabitants by age and sex</strong></span></span></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Predicted values and 95% credible intervals from the spline model MeanCases ~ Sex + s(Age, by = Sex, k = 6).</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Age\">Age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sex\">Sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Predicted\">Predicted mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI_low\">95% CI (low)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI_high\">95% CI (high)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">52.7</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">48.7</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">56.8</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">2.75</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">71.7</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">69.8</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">73.6</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">5.50</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">80.8</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">78.8</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">82.9</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">8.25</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">75.0</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">73.2</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">76.7</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">11.00</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Women</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">59.2</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">56.0</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">62.5</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">59.7</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">56.0</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">63.4</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">2.75</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">92.9</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">91.1</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">94.7</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">5.50</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">109.0</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">107.0</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">111.1</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">8.25</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">99.8</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">98.0</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">101.5</td></tr>\n    <tr><td headers=\"Age\" class=\"gt_row gt_right\">11.00</td>\n<td headers=\"Sex\" class=\"gt_row gt_left\">Men</td>\n<td headers=\"Predicted\" class=\"gt_row gt_right\">73.6</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">70.4</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">76.7</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nAnd finally in Word format:\n\n\n\n\n::: {#tbl-AgeSex_relation-Word .cell}\n\n```{.r .cell-code}\nlibrary(flextable)\nlibrary(officer)\nlibrary(dplyr)\n\n# Start from the same cleaned data\nrel_age_sex_ft_dat <- rel_age_sex %>%\n  transmute(\n    Age       = Age,\n    Sex       = Sex,\n    Predicted = round(Predicted, 1),\n    CI        = sprintf(\"%.1f, %.1f\", CI_low, CI_high)\n  )\n\nage_sex_relation_ft <- rel_age_sex_ft_dat %>%\n  flextable() %>%\n  set_header_labels(\n    Age       = \"Age\",\n    Sex       = \"Sex\",\n    Predicted = \"Predicted mean\",\n    CI        = \"95% CI\"\n  ) %>%\n\n  theme_apa_flextable() %>%\n  align(part = \"header\", align = \"center\") %>%\n  bold(part = \"header\", bold = TRUE) %>%\n  align(j = c(\"Predicted\", \"CI\"), align = \"right\", part = \"body\") %>%\n  add_footer_lines(\n    values = \"Note. Predicted mean number of consultations per 10,000 inhabitants and 95% credible intervals from the spline model.\"\n  ) %>%\n  align(part = \"footer\", align = \"left\")\n\n# Export to Word\nsave_as_docx(\n  \"Table X. Model-based consultation rates per 10,000 inhabitants by age and sex\" = age_sex_relation_ft,\n  path = \"Tables/AgeSex_relation.docx\"\n)\n```\n:::\n\n\n\n\n### Derivatives Plot\n\nWe then visualise these predictions as in the attached figure: solid lines give the posterior means by age for each sex, and ribbons represent 95% credible intervals.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot\nAge_Sex_relation_fig <- rel_age_sex %>%\n  ggplot(aes(x = Age, y = Predicted, colour = Sex, fill = Sex)) +\n  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),\n              alpha = 0.2, colour = NA) +\n  geom_line(size = 1.2) +\n  scale_color_manual(values = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n  scale_fill_manual(values  = c(\"Men\" = \"#00BFC4\", \"Women\" = \"#F8766D\")) +\n  labs(\n    x = \"Age\",\n    y = \"Number of consultations\\nper 10,000 (reference population)\",\n    caption = \"Model: MeanCases ~ Sex + s(Age, by = Sex, k = 6)\"\n  ) +\n  Plot_theme +\n  theme(\n    legend.position  = c(0.9, 0.85),\n    legend.direction = \"vertical\"\n  )\n\nggsave(\n  Age_Sex_relation_fig,\n  filename = \"Plots/Age_Sex_relation_fig.png\",\n  width    = 12,\n  height   = 12,\n  units    = \"cm\"\n)\n\nAge_Sex_relation_fig\n```\n\n::: {.cell-output-display}\n![Model-based age trajectories of mean consultation rates per 10,000 inhabitants by sex.](3_Consultation_MostFrequent_files/figure-html/fig-Age_Sex_plot-1.png){#fig-Age_Sex_plot width=576}\n:::\n:::\n\n\n\n\nThe plot shows parallel, slightly curved trajectories, with men consistently above women and both sexes peaking in early school age.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}